### ISSUE TITLE
The problem of using log4j2 as an agent log printing framework in JDK11 environment

### ISSUE THREAD

**Issue by JinyangRao** [pinpoint-apm/pinpoint#10268]
**Question：**
Due to my use of an earlier version of the branch, I upgraded the logging framework of the relevant agent according to ISSUE: log4j ------>log4j2, which worked well on JDK8 version. However, when the JDK version of the agent was upgraded to 11, inexplicably strange errors occurred:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.IllegalAccessError: symbolic reference class is not accessible: class java.lang.invoke.LambdaMetafactory, from org.apache.logging.log4j.util.StackLocator (module pinpoint.agent)

please help me~！

**Comment by emeroad** [comment]
log4j1 and log4j2 are not compatible.

If an upgrade is necessary due to a security vulnerability.
Replace log4j1 with reload4j.
https://reload4j.qos.ch/

**Comment by emeroad** [comment]
[logger system](https://github.com/pinpoint-apm/pinpoint/blob/master/profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java)
[java9 module permission](https://github.com/pinpoint-apm/pinpoint/blob/master/bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java#L110)

Would you like to take a look at the module above?

**Comment by JinyangRao** [comment]
> [logger system](https://github.com/pinpoint-apm/pinpoint/blob/master/profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java) [java9 module permission](https://github.com/pinpoint-apm/pinpoint/blob/master/bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java#L110)
> 
> Would you like to take a look at the module above?

Hi~！Woonduk, morning~！
I have merged several classes you mentioned, the relevant code of log4j2, and the implementation of JDK9 and JDK11. Through self testing, log4j2 can print logs, but there will be an exception **cannot initialize scripting support because this JRE does not support it. java. lang. NoClassDefFoundError: javax/script/ScriptEngineManager.** 

**The exception detail log is as follows:**
2023-09-04 08:57:40,868 main INFO Cannot initialize scripting support because this JRE does not support it. java.lang.NoClassDefFoundError: javax/script/ScriptEngineManager
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.script.ScriptManager.<init>(ScriptManager.java:70)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:225)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:293)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:626)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:684)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:237)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:230)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.LogManager.getContext(LogManager.java:289)


Do you have any suggestions for repair? Although it does not affect usage.
Seeing the same issue on Google, I'm not sure if there is really a compatibility issue with log4j2 and jdk11.
https://stackoverflow.com/questions/53714010/log4j2-slf4j-and-java-11

**Comment by JinyangRao** [comment]
╮(╯﹏╰）╭ 
I resolved this issue by upgrading log4j2 version to 2.20.0.
 Can we say that the lower versions of log4j2 have always had this problem?

**Comment by emeroad** [comment]
This is a warning log caused by the removal of JavaScript Engine in java11, so it does not affect operation.
