### ISSUE TITLE
pinpont-1.8.5, only jvm data and there is no data

### ISSUE THREAD

**Issue by 1994phone** [pinpoint-apm/pinpoint#10322]
I  installed pinpoint by docker, 9994、9995、9996 port is open,  three servers, the first server installs pinpoint and other components, the service data deployed by the second server is normally displayed, the project data deployed by the third server can not be displayed, only the jvm data can be seen, what is it related to? jdk version? The Internet?
url: http://124.221.113.251:8079/
<img width="1231" alt="image" src="https://github.com/pinpoint-apm/pinpoint/assets/144759205/d34b209a-02ce-411e-b127-b4487ac32b0a">
<img width="1275" alt="image" src="https://github.com/pinpoint-apm/pinpoint/assets/144759205/698956e0-f758-4784-b6c2-a160a926a76e">

**Comment by emeroad** [comment]
https://pinpoint-apm.gitbook.io/pinpoint/getting-started/installation#configuration-2

Check UDP port of 9995/9996.

**Comment by 1994phone** [comment]
> 
![image](https://github.com/pinpoint-apm/pinpoint/assets/144759205/143bbf04-501a-409e-b3b4-fbc33cbbe87b)
![image](https://github.com/pinpoint-apm/pinpoint/assets/144759205/53542865-5fa4-49bc-b5ed-754418410297)

**Comment by 1994phone** [comment]
> 



> https://pinpoint-apm.gitbook.io/pinpoint/getting-started/installation#configuration-2
> 
> Check UDP port of 9995/9996.

port of 9996 is not narmal , occur java.net.SocketTimeoutException: Receive timed out
        at java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:149)
        at java.net.DatagramSocket.receive(DatagramSocket.java:812)
        at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
        at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
        at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPSpan(NetworkAvailabilityChecker.java:92)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:66)
UDP-SPAN:// 124.221.113.251
    => 124.221.113.251:9996 [FAIL] by use sh networktest.sh

**Comment by emeroad** [comment]
Ask your network admin why udp is not working.
