### ISSUE TITLE
Failed to load plugin class com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin

### ISSUE THREAD

**Issue by gaoyunzhan** [pinpoint-apm/pinpoint#10404]
wildfly-8.2.0.Final  and pinpoint-agent-2.2.1
get error log:
10-13 11:07:51.051 [ JCA PoolFiller] ERROR c.n.p.p.t.BaseClassFileTransformer       -- Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:vfs:/content/ojdbc6-11.2.0.1.0.jar cl:ModuleClassLoader for Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader ctxCl:ModuleClassLoader for Module "org.jboss.ironjacamar.impl:main" from local module loader @2643d762 (finder: local module finder @6403e24c (roots: /app/mecoolapp/wildfly-8.2.0.Final_mijia/modules,/app/mecoolapp/wildfly-8.2.0.Final_mijia/modules/system/layers/base)) agentCl:ParallelClassLoader@666988784{name='pinpoint.agent'} Cause:com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer load fail Caused by:Failed to load plugin class com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer with classLoader ModuleClassLoader for Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader
com.navercorp.pinpoint.exception.PinpointException: com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer load fail Caused by:Failed to load plugin class com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer with classLoader ModuleClassLoader for Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader
	at com.navercorp.pinpoint.profiler.plugin.DynamicTransformCallbackProvider.getTransformCallback(DynamicTransformCallbackProvider.java:53) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:65) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.transformer.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56) [pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.transformer.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:87) [pinpoint-profiler-2.2.1.jar:2.2.1]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [?:1.8.0_382]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [?:1.8.0_382]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_382]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) [?:1.8.0_382]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.Module.loadModuleClass(Module.java:568) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_382]
	at java.lang.Class.forName(Class.java:264) [?:1.8.0_382]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:444) [ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:322) [ironjacamar-jdbc-1.1.9.Final.jar!/:1.1.9.Final]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:354) [ironjacamar-jdbc-1.1.9.Final.jar!/:1.1.9.Final]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:288) [ironjacamar-jdbc-1.1.9.Final.jar!/:1.1.9.Final]
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:1166) [ironjacamar-core-impl-1.1.9.Final.jar!/:1.1.9.Final]
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.fillTo(SemaphoreArrayListManagedConnectionPool.java:1030) [ironjacamar-core-impl-1.1.9.Final.jar!/:1.1.9.Final]
	at org.jboss.jca.core.connectionmanager.pool.mcp.PoolFiller.run(PoolFiller.java:97) [ironjacamar-core-impl-1.1.9.Final.jar!/:1.1.9.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
Caused by: com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer with classLoader ModuleClassLoader for Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:70) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:163) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.DynamicTransformCallbackProvider.getTransformCallback(DynamicTransformCallbackProvider.java:49) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	... 27 more
Caused by: com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer with classLoader ModuleClassLoader for Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:77) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:65) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:163) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.DynamicTransformCallbackProvider.getTransformCallback(DynamicTransformCallbackProvider.java:49) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	... 27 more
Caused by: java.lang.RuntimeException: com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer from [Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader]
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.loadClass(PlainClassLoaderHandler.java:196) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:126) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:74) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:65) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:163) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.DynamicTransformCallbackProvider.getTransformCallback(DynamicTransformCallbackProvider.java:49) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	... 27 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$CallableStatementTransformer from [Module "deployment.ojdbc6-11.2.0.1.0.jar:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) ~[?:?]
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.loadClass(PlainClassLoaderHandler.java:190) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:126) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:74) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:65) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:163) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	at com.navercorp.pinpoint.profiler.plugin.DynamicTransformCallbackProvider.getTransformCallback(DynamicTransformCallbackProvider.java:49) ~[pinpoint-profiler-2.2.1.jar:2.2.1]
	... 27 more

Is the plugin ojdbc6-11.2.0.1.0.jar version lower ?wihch version i need to got?
Thanks to answer

**Comment by emeroad** [comment]
It seems to be a problem with wildfly.
Currently pinpoint is not very interested in supporting wlidfly.

Can you deploy your application on Tomcat?

**Comment by gaoyunzhan** [comment]
Tasnks for answer
Probably not,Currently, there are not many resources invested in this project。

**Comment by gaoyunzhan** [comment]
i can try to deploy my application on tomcat for test
