### ISSUE TITLE
postgre jdbc issue, (버전과 서버 분리에 따른 에러 질의)

### ISSUE THREAD

**Issue by leon4652** [pinpoint-apm/pinpoint#10653]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [v] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

### 문의

안녕하세요. Agent의 추적 방법에 대해 문의드립니다.

상황 1. 
기존 서버의 경우 tomcat이 설치된 내부 서버에 postgre DB가 같이 존재하여 트랜잭션 및 토폴로지가 명확하게 추적이 되었습니다. 이때의 postgreSQL 버전은 14.5 버전입니다.

상황 2.
새롭게 설치한 Agent의 경우 Tomcat 서버(A)와 JDBC로 연결된 Postgre DB가 존재하는 서버(B)로 분리되어 추적을 하지 못하는 상황입니다. 또한, 해당 postgreSQL 버전은 16.1 버전입니다.

현재 문제 상황이 DB 버전 문제인지, 혹은 다른 외부 서버에 DB가 존재하여 연결에 실패한 것인지 모호한 상황입니다. 
이 경우 어느 부분을 변경해야 할 지 조언을 구하고자 issue를 작성하였습니다.  
(2.3.3이 postgreSQL 16 버전을 지원하는지도 문의드립니다.)  

현재 제가 파악한 부분은 "com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate, 이 클래스 내에서 transform 메서드가 호출되는 도중에 NotFoundInstrumentException"이 발생되었다는 부분입니다.

(수정)
https://github.com/pinpoint-apm/pinpoint/issues/6750
해당 이슈를 참고하였을 때, 현재 2.3.3 버전의 pinpoint 내부 plugin 중 postgresql부분을 건드려야 할 것 같은데, 이 부분이 맞는지도 문의드립니다.  

### 첨부

버전 :  
pinpoint : 2.3.3  
hbase : 1.4.6  
flink : 1.6.3  
java : 1.8

postgresql : 16.1 (현재 오류 발생)

Agent Log :  
```
01-30 15:34:10.010 [nfoSender-Timer] INFO  c.n.p.p.AgentInfoSender                  -- AgentInfo sent.
01-30 15:34:10.010 [           main] ERROR c.n.p.p.t.BaseClassFileTransformer       -- Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:jar:file:/경로.jar!/ cl:org.springframework.boot.loader.LaunchedURLClassLoader@27df0f3d ctxCl:TomcatEmbeddedWebappClassLoader
  context: ROOT
  delegate: true
----------> Parent Classloader:
org.springframework.boot.loader.LaunchedURLClassLoader@27df0f3d
 agentCl:ParallelClassLoader@401625763{name='pinpoint.agent'} Cause:com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find constructor with parameter types: [org.postgresql.util.HostSpec[], java.lang.String, java.lang.String, java.util.Properties, java.lang.String]
com.navercorp.pinpoint.exception.PinpointException: com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find constructor with parameter types: [org.postgresql.util.HostSpec[], java.lang.String, java.lang.String, java.util.Properties, java.lang.String]
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:66) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.transformer.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.transformer.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:90) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) ~[?:1.8.0_352]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) ~[?:1.8.0_352]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_352]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_352]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_352]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_352]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_352]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_352]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_352]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_352]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[bootfile-0.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.4.0.jar!/:42.4.0]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.4.0.jar!/:42.4.0]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:?]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[spring-jdbc-5.3.16.jar!/:5.3.16]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[spring-jdbc-5.3.16.jar!/:5.3.16]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-5.3.16.jar!/:5.3.16]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330) ~[spring-jdbc-5.3.16.jar!/:5.3.16]
	at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:162) ~[spring-boot-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateDefaultDdlAutoProvider.getDefaultDdlAuto(HibernateDefaultDdlAutoProvider.java:42) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.lambda$getVendorProperties$1(HibernateJpaConfiguration.java:130) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateSettings.getDdlAuto(HibernateSettings.java:41) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineDdlAuto(HibernateProperties.java:143) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.getAdditionalProperties(HibernateProperties.java:103) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineHibernateProperties(HibernateProperties.java:95) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.getVendorProperties(HibernateJpaConfiguration.java:132) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.entityManagerFactory(JpaBaseConfiguration.java:132) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
```

**Comment by smilu97** [comment]
Hi. I think `PostgreSqlPlugin` [implementation](https://github.com/pinpoint-apm/pinpoint/blob/master/plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/PostgreSqlPlugin.java#L381) looks wrong. The parameters description is currently different with [this](https://github.com/element-doo/postgresql-jdbc/blob/ce1cc57676e7782e5af395cff5b16923c067c9b7/org/postgresql/jdbc3/Jdbc3Connection.java#L21)

Maybe we need time to fix this. Thank you for reporting

**Comment by smilu97** [comment]
It seems that you can workaround this issue at least if you upgrade your postgresql-jdbc driver. I think this problem occurs when pinpoint agent tries to intercept legacy APIs from old postgresql-jdbc

**Comment by smilu97** [comment]
Pinpoint agent looks now supporting pgjdbc version at least [REL9_3_1100](https://github.com/pgjdbc/pgjdbc/tree/REL9_3_1100). They changed constructor parameters of `JdbcXXConnection` classes around that version.

REPL9_3 had been released about 11 years ago, so I think enhancing pinpoint to support that legacy version is not good idea.

**Comment by smilu97** [comment]
Latest `PgConnection` constructor was changed. The plugin need to be adapted to it.

Sorry for confusing

**Comment by jaehong-kim** [comment]
@smilu97 
This is a patched issue in version 2.4.0. - Update postgresql plugin. Supports version 42.3.2 and above. #8730

Thank you.

**Comment by leon4652** [comment]
@jaehong-kim @smilu97 
도움에 너무나도 감사드립니다. 해당 DB를 사용하려면 2.4버전 위로 버전을 올려야겠네요.
좋은 하루 되시길 바랍니다. :)
