### ISSUE TITLE
Application isnt loading the agent properly

### ISSUE THREAD

**Issue by satyakonkimalla** [pinpoint-apm/pinpoint#10727]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/2.0.4
#### Describe your problem**
I have upgraded application jdk from 11 to 17 and restarted the service, pinpoint agent isnt loading properly 

2024-03-01 14:54:24 [ERROR](c.n.p.p.BaseClassFileTransformer   ) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:jar:file:/app.jar!/BOOT-INF/lib/spring-context-6.0.9.jar!/ cl:org.springframework.boot.loader.LaunchedURLClassLoader@4fa9ab6 ctxCl:org.springframework.boot.loader.LaunchedURLClassLoader@4fa9ab6 agentCl:Java9ClassLoader{name=pinpoint.agent} com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader@5b6f7412 Cause:Cannot invoke "com.navercorp.pinpoint.bootstrap.instrument.InstrumentClass.getDeclaredMethod(String, String[])" because "target" is null
java.lang.NullPointerException: Cannot invoke "com.navercorp.pinpoint.bootstrap.instrument.InstrumentClass.getDeclaredMethod(String, String[])" because "target" is null
	at com.navercorp.pinpoint.plugin.spring.async.SpringAsyncPlugin$AsyncTaskExecutorTransform.doInTransform(SpringAsyncPlugin.java:93)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:66)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.javamodule.ClassFileTransformerModuleHandler.transform(ClassFileTransformerModuleHandler.java:61)
	at com.navercorp.pinpoint.bootstrap.java9.module.ClassFileTransformerModuleWrap.transform(ClassFileTransformerModuleWrap.java:46)
	at java.instrument/sun.instrument.TransformerManager.transform(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.resolve(FilteringSpringBootCondition.java:108)
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.isPresent(FilteringSpringBootCondition.java:140)
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter$2.matches(FilteringSpringBootCondition.java:128)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcome(OnClassCondition.java:223)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcome(OnClassCondition.java:207)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcomes(OnClassCondition.java:197)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.resolveOutcomes(OnClassCondition.java:186)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition.resolveOutcomesThreaded(OnClassCondition.java:68)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition.getOutcomes(OnClassCondition.java:52)
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.match(FilteringSpringBootCondition.java:49)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$ConfigurationClassFilter.filter(AutoConfigurationImportSelector.java:366)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:131)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:430)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:793)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:723)

#### What have you done?
Steps you have taken to trigger the problem, for example:
re installed the pinpoint using docker compose
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2024-03-01 14:54:24 [ERROR](c.n.p.p.BaseClassFileTransformer   ) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:jar:file:/app.jar!/BOOT-INF/lib/spring-context-6.0.9.jar!/ cl:org.springframework.boot.loader.LaunchedURLClassLoader@4fa9ab6 ctxCl:org.springframework.boot.loader.LaunchedURLClassLoader@4fa9ab6 agentCl:Java9ClassLoader{name=pinpoint.agent} com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader@5b6f7412 Cause:Cannot invoke "com.navercorp.pinpoint.bootstrap.instrument.InstrumentClass.getDeclaredMethod(String, String[])" because "target" is null
java.lang.NullPointerException: Cannot invoke "com.navercorp.pinpoint.bootstrap.instrument.InstrumentClass.getDeclaredMethod(String, String[])" because "target" is null
	at com.navercorp.pinpoint.plugin.spring.async.SpringAsyncPlugin$AsyncTaskExecutorTransform.doInTransform(SpringAsyncPlugin.java:93)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:66)
	at pinpoint.agent/pinpoint

4. No trace shows up in the web UI (see web log below)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by intr3p1d** [comment]
Java 17 is supported by pinpoint after the version `2.3.x`.
We recommend that you upgrade your version of Pinpoint to match your JDK version and try running it again.

Java version required to run Pinpoint:

| Pinpoint Version | Agent | Collector | Web | Flink |
|------------------|-------|-----------|-----|-------|
| 2.0.x            | 6-13  | 8         | 8   | 8     |
| 2.1.x            | 6-14  | 8         | 8   | 8     |
| 2.2.x            | 7-14  | 8         | 8   | 8     |
| 2.3.x            | 7-17  | 8         | 8   | 8     |
| 2.4.x            | 7-18  | 11        | 11  | 11    |
| 2.5.x            | 8-19  | 11        | 11  | 11    |
| 3.0.x            | 8-21  | 17        | 17  | 17    |


 You can check compatibility at the link here : https://github.com/pinpoint-apm/pinpoint?tab=readme-ov-file#compatibility
