### ISSUE TITLE
ClassLoader 异常

### ISSUE THREAD

**Issue by woniusnai** [pinpoint-apm/pinpoint#10969]
java应用启动方式为 java -jar app.jar -javaagent:/pinpoint......

错误信息：java.lang.ClassNotFoundException: com.sinfusi.freedom.convert.IConvert
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at com.navercorp.pinpoint.bootstrap.classloader.ParallelClassLoader.loadClass(ParallelClassLoader.java:105)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: com/sinfusi/freedom/convert/IConvert
	at java.lang.ClassLoader.defineClass1(ClassLoader.java)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at sun.reflect.GeneratedMethodAccessor357.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1183)
	at javassist.ClassPool.toClass(ClassPool.java:1164)
	... 19 common frames omitted
Wrapped by: javassist.CannotCompileException: by java.lang.NoClassDefFoundError: com/sinfusi/freedom/convert/IConvert
	at javassist.ClassPool.toClass(ClassPool.java:1170)
	at javassist.ClassPool.toClass(ClassPool.java:1113)
	at javassist.ClassPool.toClass(ClassPool.java:1071)
	at javassist.CtClass.toClass(CtClass.java:1275)
	at com.sinfusi.freedom.convert.ConvertUtil.createConve

应用自身的类加载器使用了pinpoint的，导致我的应用异常，这是什么原因呢？

**Comment by emeroad** [comment]
It seems to be a very old version of the agent that uses Javassist.
Javassist has been deprecated for a long time.
Please upgrade to the latest version using ASM.

**Comment by woniusnai** [comment]
<javassist.version>3.20.0-GA</javassist.version>
需要我升级到3.30吗 还是改用ASM？
