### ISSUE TITLE
Spring ClientHttpRequest is not visible from class loader: ParallelClassLoader@772777427{name='pinpoint.agent'}

### ISSUE THREAD

**Issue by xiaoxing139** [pinpoint-apm/pinpoint#11052]
#### Prerequisites
An exception has occurred when user send a request in asynchronous thread.
**User Code:**
```java
CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
    // something to do
    ClientHttpRequest request = createRequest(url, method);
    ProxyFactory factory = new ProxyFactory(request);
    // something to do
    factory.setInterfaces(ClientHttpRequest.class);
    ClientHttpRequest proxyClientHttpRequest = (ClientHttpRequest) factory.getProxy();
    // something to do
});
```
**Exception:**
```java
Exception when request uri:/xxx/xxx/xxx/list
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: interface org.springframework.http.client.ClientHttpRequest is not visible from class loader: ParallelClassLoader@772777427{name='pinpoint.agent'}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_382]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_382]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_382]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_382]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_382]
Caused by: java.lang.IllegalArgumentException: interface org.springframework.http.client.ClientHttpRequest is not visible from class loader: ParallelClassLoader@772777427{name='pinpoint.agent'}
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581) ~[?:1.8.0_382]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[?:1.8.0_382]
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[?:1.8.0_382]
	at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[?:1.8.0_382]
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[?:1.8.0_382]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[?:1.8.0_382]
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:126) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:118) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:97) ~[spring-aop-5.3.33.jar:5.3.33]
	at com.xxx.VegaRestTemplate.doExecute(VegaRestTemplate.java:169) ~[xxx-[********].RELEASE.jar:[********].RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:738) ~[spring-web-5.3.33.jar:5.3.33]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:647) ~[spring-web-5.3.33.jar:5.3.33]
```

#### What version of pinpoint are you using?
2.5.2

#### Describe the bug
We found pinpoint-agent use `ForkJoinPool.commonPool()` to create ThreadPool with `cacheBuilder.build()` when sending MetaData, but user use `ForkJoinPool.commonPool()` too.

**Pinpoint**
```java
package com.navercorp.pinpoint.profiler.cache;

public class SimpleCache<T> {
    private ConcurrentMap<T, Result> createCache(int maxCacheSize) {
        final Caffeine<Object, Object> cacheBuilder = Caffeine.newBuilder();
        cacheBuilder.initialCapacity(maxCacheSize);
        cacheBuilder.maximumSize(maxCacheSize);
        Cache<T, Result> localCache = cacheBuilder.build();
        return localCache.asMap();
    }
}
```
**Caffeine**
```java
package com.github.benmanes.caffeine.cache;

public final class Caffeine<K, V> {
  @NonNull
  Executor getExecutor() {
    return (executor == null) ? ForkJoinPool.commonPool() : executor;
  }
}
```

Is it a bug when creating `SimpleCache` that pinpoint-agent not sets `Executor`? 
Has it a problem of user code？

**Comment by emeroad** [comment]
Hello
Thank you for your contribution.
It seems like bad code for the caffine cache to share the JDK common pool. We will fix this bug immediately.

However, further investigation is needed to determine whether this problem is the cause of the class loader error.
We are currently reproducing the problem.

**Comment by emeroad** [comment]
```java
CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
     // classloader debug~~~~~
     ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
     System.out.println("contextClassLoader" + contextClassLoader);

    ClassLoader defaultClassLoader = ClassUtils.getDefaultClassLoader();
    System.out.println("spring defaultClassLoader" + defaultClassLoader);
     // classloader debug~~~~

    // something to do
    ClientHttpRequest request = createRequest(url, method);
    ProxyFactory factory = new ProxyFactory(request);
    // something to do
    factory.setInterfaces(ClientHttpRequest.class);
    ClientHttpRequest proxyClientHttpRequest = (ClientHttpRequest) factory.getProxy();
    // something to do
});

```

It is necessary to investigate whether the context class loader has been set incorrectly.
Could you add the debug code above?

**Comment by emeroad** [comment]
```java
@RequestMapping(value = "/spring/mvc/async/callableFuture")
    public String asyncCallableFuture() throws ExecutionException, InterruptedException {

        ClassLoader cl1 = ClassUtils.getDefaultClassLoader();
        System.out.println("-----context outer ClassLoader: " + cl1);

        CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
            // Executed by fork join pool.
            ClassLoader defaultCl = ClassUtils.getDefaultClassLoader();
            System.out.println("-----context in: " + defaultCl);
            System.out.println("-----context thread: " + Thread.currentThread().getName());
            System.out.println("-----TestString Cl:" + TestString.class.getClassLoader());

            HelloStringTest helloStringTest = new HelloStringTest();
            ProxyFactory factory = new ProxyFactory(helloStringTest);
            factory.setInterfaces(TestString.class);
            TestString proxy = (TestString) factory.getProxy();
            System.out.println("proxy:" + proxy.test());
            
            try {
                TimeUnit.SECONDS.sleep(3);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            return "hello";
        });

        return future.get();
    }
```

```
-----context outer ClassLoader: ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@633cc6b5

-----context in: ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@633cc6b5

-----context thread: ForkJoinPool.commonPool-worker-9
-----TestString Cl:ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@633cc6b5
```

I succeeded in reproducing the problem.

It appears to be a Caffine Executor issue.
We confirmed that if you modify the Caffine exeuctor according to your opinion, no problem occurs.

Temporary patch example
```java
final Caffeine<Object, Object> cacheBuilder = Caffeine.newBuilder();
cacheBuilder.initialCapacity(maxCacheSize);
cacheBuilder.executor(Executors.newSingleThreadExecutor());  <- fix
cacheBuilder.maximumSize(maxCacheSize);
Cache<T, Object> localCache = cacheBuilder.build();
this.cache = localCache.asMap();
```

**Comment by emeroad** [comment]
```java
@Test
    public void test() throws InterruptedException {
        ForkJoinPool pool = ForkJoinPool.commonPool();

        URLClassLoader urlClassLoader = new URLClassLoader(new URL[0]);
        CountDownLatch latch1 = new CountDownLatch(1);
        pool.execute(() -> {
            ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
            System.out.println("ForkJoinThread originalCl:" + contextClassLoader);
            latch1.countDown();
        });

        latch1.await();

        CountDownLatch latch2 = new CountDownLatch(1);
        pool.execute(new Runnable() {
            @Override
            public void run() {
                Thread.currentThread().setContextClassLoader(urlClassLoader);
                System.out.println("ForkJoinThread change context");
                latch2.countDown();
            }
        });
        latch2.await();

        CountDownLatch latch3 = new CountDownLatch(1);
        pool.execute(() -> {
            ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
            System.out.println("ForkJoinThread cl:" + contextClassLoader);
            latch3.countDown();
        });
        latch3.await();
    }
```

```
ForkJoinThread originalCl:jdk.internal.loader.ClassLoaders$AppClassLoader@1dbd16a6
ForkJoinThread change context
ForkJoinThread cl:java.net.URLClassLoader@3e8f7922
```

I found the root cause of this problem.
Changing ContextClassLoader from WorkThread in `ForkJoinPool.commonPool()` is the root cause of this problem.

Agents should not use the JDK commons pool.

**Comment by emeroad** [comment]
## Workaround
Modify to use a dedicated thread pool.
```java
CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
     // Execute Task
}, executor); <-  Assign a dedicated executor
```
