### ISSUE TITLE
pinpoint 3.0.0, java version issue

### ISSUE THREAD

**Issue by huijikim00** [pinpoint-apm/pinpoint#11591]
I'm using Pinpoint 3.0.0.
Currently, I'm using Java version 21.
While using Pinpoint, the following log occurs only with Java 21 version, and the pinpoint agent does not run normally.
I understand that from Pinpoint version 3.0.0, Java 21 version can be used,
but can I get some information about this log?

log info

```java
10-17 00:27:11.989 INFO  PinpointStarter                     : pinpoint agent started normally.

        88888888ba   88  888b      88  88888888ba     ,ad8888ba,    88  888b      88  888888888888
        88      ,8P  88  88 `8b    88  88      ,8P  d8'        `8b  88  88 `8b    88       88
        88aaaaaa8P'  88  88  `8b   88  88aaaaaa8P'  88    da    88  88  88  `8b   88       88
        88           88  88    `8b 88  88           Y8,        ,8P  88  88    `8b 88       88
        88           88  88      `888  88             `"Y8888Y"'    88  88      `888       88

                               https://github.com/pinpoint-apm/pinpoint

 ::                                        Pinpoint Version ::                      3.0.1-SNAPSHOT
 ::                       pinpoint.profiler.profiles.active ::                             release
 ::                                pinpoint.applicationName ::                   d-spd-product-api
 ::                                      pinpoint.agentName ::                   d-spd-product-api
 ::                               profiler.transport.module ::                                GRPC
 ::                    profiler.transport.grpc.collector.ip ::                        200.0.10.235
 ::            profiler.transport.grpc.agent.collector.port ::                                9991
 ::         profiler.transport.grpc.metadata.collector.port ::                                9991
 ::             profiler.transport.grpc.stat.collector.port ::                                9992
 ::             profiler.transport.grpc.span.collector.port ::                                9993
 ::                  profiler.spandatasender.transport.type ::                                 UDP
 ::                  profiler.statdatasender.transport.type ::                                 UDP
 ::                                profiler.sampling.enable ::                                true
 ::                                  profiler.sampling.type ::                            COUNTING
 ::                profiler.sampling.counting.sampling-rate ::                                  20
 ::                 profiler.sampling.percent.sampling-rate ::                                 100

openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
WARN StatusConsoleListener No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
WARN StatusConsoleListener Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
``` 

```java
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] bootstrap unnamedModule:unnamed module @776ec8df
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] platform unnamedModule:unnamed module @77468bd9
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] system unnamedModule:unnamed module @12bb4df8
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] defineModule classLoader: Java9ClassLoader{name=pinpoint.agent} com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader@16f65612
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] defineModule classLoader-unnamedModule: unnamed module @7b3300e5
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] packages:[io.netty.handler.codec.rtsp, com.navercorp.pinpoint.profiler.context.compress, com.google.protobuf, org.checkerframework.checker.calledmethods.qual, org.apache.logging.log4j.core.config.plugins.validation.validators, com.navercorp.pinpoint.profiler.monitor.metric.cpu.ibm, com.navercorp.pinpoint.profiler.monitor.collector.activethread, io.grpc.protobuf.lite, io.netty.handler.codec.serialization, io.micrometer.core.instrument.binder.httpcomponents.hc5, io.netty.channel.socket.nio, com.navercorp.pinpoint.profiler.instrument.classreading, com.google.cloud, com.google.inject, com.navercorp.pinpoint.profiler.monitor.collector.cpu, org.checkerframework.framework.qual, io.netty.handler.codec.protobuf, com.navercorp.pinpoint.profiler.monitor.metric, com.navercorp.pinpoint.profiler.plugin.filter, io.github.resilience4j.core.registry, io.netty.handler.flush, com.navercorp.pinpoint.profiler.context.provider.stat.cpu, org.yaml.snakeyaml.emitter, io.netty.handler.ssl, com.navercorp.pinpoint.profiler.monitor.metric.buffer, io.micrometer.core.instrument.push, org.checkerframework.common.returnsreceiver.qual, com.navercorp.pinpoint.profiler.instrument, org.apache.logging.log4j.core.layout, org.apache.logging.log4j.core.message, com.google.gson.internal, com.navercorp.pinpoint.profiler.shutdown, io.micrometer.core.instrument.binder.hystrix, io.netty.util.internal, org.checkerframework.common.util.report.qual, org.apache.logging.log4j, com.github.benmanes.caffeine.cache.stats, io.micrometer.core.instrument.binder.system, org.apache.logging.log4j.core.appender.rolling.action, org.slf4j.event, org.apache.logging.log4j.core.tools.picocli, com.navercorp.pinpoint.profiler.context.provider.stat.filedescriptor, org.HdrHistogram.packedarray, org.apache.logging.log4j.core.appender.rewrite, com.google.common.base, io.netty.handler.codec.spdy, io.netty.channel.internal, com.google.errorprone.annotations, com.google.common.cache, com.navercorp.pinpoint.profiler.jdbc, com.navercorp.pinpoint.profiler.monitor.metric.cpu.oracle, io.micrometer.registry.otlp, io.micrometer.context, io.github.resilience4j.core.exception, com.google.longrunning, org.yaml.snakeyaml.comments, org.apache.logging.log4j.core.appender.mom.kafka, com.navercorp.pinpoint.profiler.context.storage, org.apache.logging.log4j.core.config.yaml, org.slf4j, com.google.rpc, io.micrometer.core.instrument.noop, com.navercorp.pinpoint.profiler.monitor.metric.activethread, org.apache.logging.log4j.core.selector, com.navercorp.pinpoint.profiler.monitor.metric.uri, io.opentelemetry.proto.collector.logs.v1, com.navercorp.pinpoint.grpc.client.interceptor, com.navercorp.pinpoint.profiler, io.micrometer.core.ipc.http, com.navercorp.pinpoint.common.profiler.message, org.apache.logging.log4j.core.config.builder.impl, com.navercorp.pinpoint.common.profiler.logging, io.vavr.match.annotation, com.navercorp.pinpoint.profiler.sampler, org.apache.logging.slf4j, com.navercorp.pinpoint.profiler.plugin.config, io.grpc.internal, com.google.cloud.audit, org.apache.logging.log4j.core.config.plugins.validation.constraints, org.apache.logging.log4j.core.osgi, org.objectweb.asm, com.google.common.math, io.opentelemetry.proto.resource.v1, io.netty.handler.codec.http, jakarta.annotation.sql, com.navercorp.pinpoint.profiler.context.annotation, io.netty.handler.traffic, org.apache.logging.log4j.core.appender.rolling, io.grpc.stub.annotations, com.google.inject.internal.aop, io.netty.handler.codec.http.cookie, com.google.rpc.context, io.micrometer.core.instrument.config.validate, com.google.api, io.micrometer.core.instrument.binder, com.google.common.base.internal, javax.annotation.processing, reactor.blockhound.integration, org.checkerframework.checker.initialization.qual, io.micrometer.common.annotation, io.micrometer.core.instrument.dropwizard, io.netty.channel, org.slf4j.helpers, com.navercorp.pinpoint.profiler.context.provider.metric, com.navercorp.pinpoint.profiler.monitor.metric.filedescriptor.ibm, org.mapstruct.control, io.micrometer.core.instrument.step, com.navercorp.pinpoint.grpc.client.config, org.mapstruct.factory, org.apache.logging.log4j.core.config.composite, org.apache.logging.log4j.core.config.plugins.convert, io.micrometer.observation.annotation, com.navercorp.pinpoint.profiler.monitor.collector.deadlock, com.google.common.primitives, com.navercorp.pinpoint.profiler.plugin, org.codehaus.mojo.animal_sniffer, org.checkerframework.checker.index.qual, com.google.type, io.vavr, io.micrometer.common, io.micrometer.core.instrument, com.google.inject.name, com.navercorp.pinpoint.profiler.context.provider.sampler, com.navercorp.pinpoint.profiler.context.active, com.google.inject.matcher, org.checkerframework.common.initializedfields.qual, org.apache.logging.log4j.core.appender, com.google.inject.internal, io.micrometer.core.instrument.observation, com.google.common.html, org.apache.logging.log4j.core.tools, com.navercorp.pinpoint.agent.plugin.proxy.apache, com.navercorp.pinpoint.profiler.instrument.classloading, org.apache.logging.log4j.core.net, org.apache.logging.log4j.core.appender.mom, com.navercorp.pinpoint.profiler.util, org.yaml.snakeyaml.composer, io.micrometer.core.instrument.binder.logging, io.netty.handler.codec, io.micrometer.core.instrument.util, com.google.gson.stream, io.netty.handler.stream, io.netty.handler.codec.http.multipart, io.netty.channel.socket, io.micrometer.core.instrument.kotlin, org.apache.logging.log4j.core.config.status, com.navercorp.pinpoint.profiler.context.provider.stat.totalthread, com.google.common.escape, com.google.thirdparty.publicsuffix, com.navercorp.pinpoint.common.buffer, org.yaml.snakeyaml.internal, javax.annotation.meta, com.navercorp.pinpoint.profiler.context.module.config, com.navercorp.pinpoint.profiler.interceptor.scope, com.navercorp.pinpoint.profiler.instrument.lambda, org.yaml.snakeyaml.error, com.google.gson.annotations, com.navercorp.pinpoint.profiler.context.id, com.navercorp.pinpoint.profiler.context.config, org.yaml.snakeyaml, com.google.inject.multibindings, org.yaml.snakeyaml.inspector, org.objectweb.asm.tree.analysis, com.navercorp.pinpoint.profiler.context.exception.storage, io.micrometer.core.instrument.config, org.checkerframework.checker.interning.qual, io.netty.handler.codec.json, io.netty.util.concurrent, com.navercorp.pinpoint.profiler.monitor.metric.deadlock, io.micrometer.core.instrument.binder.netty4, com.navercorp.pinpoint.agent.plugin.proxy.user, com.github.benmanes.caffeine.cache, com.navercorp.pinpoint.profiler.monitor.collector.loadedclass, com.navercorp.pinpoint.profiler.context.recorder, org.objectweb.asm.signature, org.apache.logging.log4j.core.util, org.apache.logging.log4j.core.script, com.navercorp.pinpoint.grpc.trace, com.navercorp.pinpoint.common.profiler.concurrent.jsr166, org.yaml.snakeyaml.tokens, com.navercorp.pinpoint.profiler.context.exception.sampler, com.navercorp.pinpoint.profiler.monitor.collector.jvmgc, com.navercorp.pinpoint.profiler.context.javamodule, org.aopalliance.aop, org.checkerframework.checker.regex.qual, com.google.inject.internal.util, io.netty.channel.unix, io.grpc, com.google.inject.util, org.checkerframework.common.value.qual, com.google.gson, com.navercorp.pinpoint.profiler.monitor.metric.filedescriptor.oracle, com.navercorp.pinpoint.profiler.context.grpc, org.checkerframework.checker.guieffect.qual, io.netty.handler.codec.http.websocketx.extensions.compression, org.yaml.snakeyaml.introspector, com.google.common.util.concurrent, com.google.common.eventbus, com.github.benmanes.caffeine.base, com.google.gson.internal.bind, io.micrometer.common.docs, com.google.common.collect, com.navercorp.pinpoint.profiler.context.provider.stat.jvmgc, io.netty.buffer, io.netty.channel.embedded, org.apache.logging.log4j.core.async, com.navercorp.pinpoint.profiler.context.provider.stat.buffer, com.navercorp.pinpoint.profiler.util.queue, com.navercorp.pinpoint.profiler.metadata, android.annotation, com.google.cloud.location, org.LatencyUtils, io.micrometer.core.aop, com.navercorp.pinpoint.profiler.context, io.netty.handler.ipfilter, org.apache.logging.log4j.core.appender.routing, io.micrometer.core.instrument.logging, io.netty.handler.codec.string, io.netty.buffer.search, io.github.resilience4j.core.predicate, org.apache.logging.log4j.core.filter.mutable, com.navercorp.pinpoint.grpc, com.navercorp.pinpoint.profiler.context.module, com.google.common.net, com.navercorp.pinpoint.io, com.navercorp.pinpoint.profiler.monitor.metric.gc, com.navercorp.pinpoint.loader.plugins, io.netty.channel.socket.oio, com.google.common.util.concurrent.internal, io.micrometer.common.util.internal.logging, com.navercorp.pinpoint.grpc.util, io.opentelemetry.proto.logs.v1, com.google.gson.internal.reflect, io.micrometer.common.lang, org.apache.logging.log4j.core.config.xml, com.navercorp.pinpoint.profiler.context.provider.stat.loadedclass, com.navercorp.pinpoint.grpc.server.flowcontrol, com.navercorp.pinpoint.profiler.context.provider.plugin, io.github.resilience4j.core.metrics, com.navercorp.pinpoint.common.profiler.concurrent.executor, com.navercorp.pinpoint.profiler.context.recorder.proxy, org.yaml.snakeyaml.extensions.compactnotation, io.micrometer.core.instrument.internal, io.netty.handler.codec.marshalling, org.yaml.snakeyaml.external.com.google.gdata.util.common.base, com.google.errorprone.annotations.concurrent, com.navercorp.pinpoint.profiler.monitor.metric.transaction, org.apache.logging.log4j.core.config.plugins, org.HdrHistogram, org.checkerframework.checker.compilermsgs.qual, io.netty.handler.ssl.util, com.navercorp.pinpoint.profiler.context.grpc.config, com.navercorp.pinpoint.profiler.interceptor.factory, com.navercorp.pinpoint.profiler.monitor.collector.totalthread, com.google.logging.type, org.apache.logging.log4j.core.config.properties, io.micrometer.core.instrument.binder.jvm, org.slf4j.spi, io.netty.util.internal.shaded.org.jctools.queues.atomic, org.apache.commons.logging.impl, com.navercorp.pinpoint.grpc.security, com.navercorp.pinpoint.grpc.channelz, org.apache.logging.log4j.core.config.arbiters, com.navercorp.pinpoint.common.profiler.trace, com.navercorp.pinpoint.common.profiler.util, org.apache.logging.log4j.core.filter, com.github.benmanes.caffeine, com.navercorp.pinpoint.profiler.receiver.grpc, io.micrometer.core.instrument.binder.okhttp3, org.checkerframework.checker.tainting.qual, com.google.common.xml, com.navercorp.pinpoint.loader.plugins.trace.yaml, com.navercorp.pinpoint.profiler.sender, com.navercorp.pinpoint.profiler.monitor.metric.response, io.netty.util.internal.shaded.org.jctools.queues, io.opentelemetry.proto.collector.trace.v1, com.navercorp.pinpoint.profiler.context.monitor.config, com.navercorp.pinpoint.profiler.context.errorhandler, com.navercorp.pinpoint.agent.plugin.proxy.common, io.netty.handler.codec.base64, org.checkerframework.checker.signedness.qual, com.navercorp.pinpoint.profiler.context.provider, org.apache.commons.logging, com.navercorp.pinpoint.grpc.server, com.navercorp.pinpoint.profiler.monitor.metric.totalthread, org.checkerframework.common.subtyping.qual, org.apache.logging.log4j.message, com.google.protobuf.compiler, com.navercorp.pinpoint.loader.service, org.checkerframework.dataflow.qual, com.google.j2objc.annotations, io.micrometer.core.instrument.binder.cache, io.netty.util.collection, com.google.common.graph, io.micrometer.observation.aop, io.netty.channel.epoll, org.objectweb.asm.commons, io.netty.handler.codec.http.websocketx.extensions, org.checkerframework.common.aliasing.qual, io.netty.resolver, org.apache.logging.log4j.core.parser, io.github.resilience4j.core.lang, org.apache.logging.log4j.status, org.apache.logging.log4j.core.util.internal, io.micrometer.core.instrument.binder.kafka, org.apache.logging.log4j.core.config, com.navercorp.pinpoint.profiler.receiver, io.netty.handler.codec.http2, io.opentelemetry.proto.trace.v1, org.checkerframework.checker.optional.qual, com.navercorp.pinpoint.profiler.context.provider.metadata, com.navercorp.pinpoint.profiler.interceptor.registry, com.navercorp.pinpoint.profiler.monitor.metric.loadedclass, io.netty.handler.codec.bytes, io.netty.handler.timeout, org.checkerframework.checker.i18nformatter.qual, org.yaml.snakeyaml.util, org.yaml.snakeyaml.resolver, org.checkerframework.checker.mustcall.qual, org.apache.logging.log4j.core.config.plugins.util, io.netty.channel.oio, io.micrometer.core.instrument.binder.jersey.server, com.navercorp.pinpoint.profiler.context.provider.stat.datasource, io.micrometer.core.instrument.distribution.pause, com.navercorp.pinpoint.common.profiler.clock, com.google.common.hash, io.micrometer.core.instrument.distribution, com.navercorp.pinpoint.profiler.context.provider.stat.transaction, org.apache.logging.log4j.core.lookup, org.checkerframework.checker.nullness.qual, io.netty.handler.ssl.ocsp, org.apache.logging.log4j.core.util.datetime, com.navercorp.pinpoint.common.profiler.concurrent, com.navercorp.pinpoint.loader.plugins.trace, org.yaml.snakeyaml.representer, com.navercorp.pinpoint.profiler.monitor.collector.buffer, com.navercorp.pinpoint.grpc.client.retry, org.yaml.snakeyaml.reader, jakarta.inject, com.navercorp.pinpoint.profiler.monitor.metric.custom, io.micrometer.observation.contextpropagation, io.netty.handler.proxy, com.navercorp.pinpoint.profiler.monitor.collector.transaction, com.navercorp.pinpoint.profiler.cache, com.navercorp.pinpoint.profiler.context.provider.grpc, org.checkerframework.checker.propkey.qual, io.netty.util.internal.logging, com.navercorp.pinpoint.profiler.sender.grpc.stream, org.apache.logging.log4j.core.time.internal, org.apache.logging.log4j.core.layout.internal, io.netty.channel.nio, com.navercorp.pinpoint.profiler.instrument.config, io.micrometer.core.instrument.binder.jetty, io.micrometer.core.instrument.binder.tomcat, io.micrometer.core.instrument.cumulative, com.navercorp.pinpoint.grpc.client, io.vavr.concurrent, io.grpc.protobuf, com.navercorp.pinpoint.profiler.instrument.transformer, io.netty.handler.codec.compression, com.navercorp.pinpoint.profiler.monitor, org.aopalliance.intercept, io.micrometer.observation, io.netty.channel.pool, com.navercorp.pinpoint.profiler.context.provider.stat.response, com.google.inject.spi, io.micrometer.observation.transport, org.apache.logging.log4j.core.config.plugins.visitors, io.micrometer.core.instrument.binder.commonspool2, com.navercorp.pinpoint.profiler.monitor.metric.memory, org.apache.logging.log4j.core.appender.nosql, com.navercorp.pinpoint.grpc.log, com.google.gson.reflect, io.micrometer.core.instrument.binder.db, org.apache.logging.log4j.core.appender.db.jdbc, org.apache.logging.log4j.core, org.apache.logging.log4j.internal, com.navercorp.pinpoint.profiler.monitor.metric.filedescriptor, com.google.inject.internal.asm, io.netty.util.internal.shaded.org.jctools.util, com.google.common.reflect, com.navercorp.pinpoint.common.profiler.sql, org.yaml.snakeyaml.external.biz.base64Coder, com.navercorp.pinpoint.grpc.server.lifecycle, com.navercorp.pinpoint.profiler.logging.jul, com.navercorp.pinpoint.profiler.context.provider.stat.deadlock, org.objectweb.asm.util, io.micrometer.observation.docs, io.netty.handler.address, org.yaml.snakeyaml.nodes, io.micrometer.core.instrument.binder.httpcomponents, org.mapstruct.util, com.google.inject.binder, org.apache.logging.log4j.core.appender.mom.jeromq, org.apache.logging.log4j.jcl, com.navercorp.pinpoint.profiler.monitor.collector, org.yaml.snakeyaml.constructor, org.apache.logging.log4j.core.net.ssl, com.navercorp.pinpoint.profiler.receiver.service, org.checkerframework.checker.fenum.qual, org.yaml.snakeyaml.serializer, io.micrometer.core.instrument.binder.mongodb, com.google.gson.internal.sql, com.navercorp.pinpoint.profiler.context.scope, io.micrometer.core.lang, io.opentelemetry.proto.common.v1, com.navercorp.pinpoint.profiler.monitor.metric.datasource, com.navercorp.pinpoint.profiler.monitor.metric.cpu, com.navercorp.pinpoint.profiler.transformer, org.yaml.snakeyaml.env, org.apache.logging.log4j.core.impl, com.navercorp.pinpoint.common.profiler.encoding, org.yaml.snakeyaml.parser, org.apache.logging.log4j.core.config.json, com.navercorp.pinpoint.profiler.instrument.interceptor, io.micrometer.core.instrument.binder.jpa, io.netty.bootstrap, org.apache.logging.log4j.util, io.netty.channel.local, io.perfmark, com.navercorp.pinpoint.profiler.monitor.collector.filedescriptor, io.vavr.control, com.navercorp.pinpoint.profiler.context.monitor, com.navercorp.pinpoint.profiler.monitor.collector.response, com.google.common.annotations, io.netty.channel.group, com.navercorp.pinpoint.profiler.context.grpc.mapper, org.apache.logging.log4j.core.jmx, com.navercorp.pinpoint.loader.plugins.profiler, io.micrometer.core.instrument.binder.grpc, io.opentelemetry.proto.collector.metrics.v1, io.grpc.util, org.apache.logging.log4j.core.jackson, org.objectweb.asm.tree, org.mapstruct, com.navercorp.pinpoint.profiler.instrument.scanner, io.netty.util.internal.svm, jakarta.annotation.security, com.navercorp.pinpoint.agent.plugin.proxy.nginx, io.netty.internal.tcnative, com.navercorp.pinpoint.profiler.context.provider.stat.activethread, org.apache.logging.log4j.core.config.plugins.validation, io.netty.handler.pcap, javax.annotation, jakarta.annotation, io.micrometer.core.instrument.search, io.netty.handler.codec.xml, io.micrometer.core.annotation, org.checkerframework.checker.formatter.qual, org.checkerframework.checker.units.qual, org.apache.logging.log4j.core.time, io.github.resilience4j.core.functions, org.checkerframework.checker.builder.qual, javax.annotation.concurrent, com.google.geo.type, io.opentelemetry.proto.metrics.v1, com.navercorp.pinpoint.profiler.context.monitor.metric, org.checkerframework.common.reflection.qual, org.apache.logging.log4j.core.appender.db, io.netty.util, io.micrometer.common.util, io.micrometer.core.instrument.docs, com.navercorp.pinpoint.profiler.logging, org.yaml.snakeyaml.scanner, com.navercorp.pinpoint.profiler.sender.grpc.metric, com.navercorp.pinpoint.profiler.context.provider.exception, com.navercorp.pinpoint.profiler.monitor.collector.datasource, org.apache.logging.log4j.spi, io.netty.handler.codec.http.websocketx, com.navercorp.pinpoint.profiler.context.exception, com.navercorp.pinpoint.profiler.monitor.micrometer, io.micrometer.core.instrument.binder.http, org.apache.logging.log4j.core.config.builder.api, com.navercorp.pinpoint.profiler.context.method, io.micrometer.core.instrument.simple, com.navercorp.pinpoint.profiler.context.exception.model, io.netty.handler.logging, io.vavr.collection, org.apache.logging.log4j.core.config.plugins.processor, io.netty.handler.codec.http.cors, io.grpc.stub, org.apache.logging.log4j.core.pattern, org.checkerframework.checker.i18n.qual, org.yaml.snakeyaml.events, com.navercorp.pinpoint.agent.plugin.proxy.app, io.netty.handler.flow, org.checkerframework.checker.lock.qual, io.micrometer.core.instrument.composite, com.navercorp.pinpoint.profiler.objectfactory, org.checkerframework.checker.signature.qual, io.grpc.netty, com.navercorp.pinpoint.profiler.context.exception.disabled, io.github.resilience4j.core, com.navercorp.pinpoint.profiler.sender.grpc, io.micrometer.core.util.internal.logging, com.google.common.io, com.google.gson.internal.bind.util, org.apache.logging.log4j.simple]
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] providers:{io.micrometer.context.ThreadLocalAccessor=[io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor], io.grpc.ServerProvider=[io.grpc.netty.NettyServerProvider], io.grpc.LoadBalancerProvider=[io.grpc.internal.PickFirstLoadBalancerProvider, io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider, io.grpc.util.OutlierDetectionLoadBalancerProvider], com.navercorp.pinpoint.agent.plugin.proxy.common.ProxyRequestMetadataProvider=[com.navercorp.pinpoint.agent.plugin.proxy.apache.ApacheRequestMetadataProvider, com.navercorp.pinpoint.agent.plugin.proxy.user.UserRequestMetadataProvider, com.navercorp.pinpoint.agent.plugin.proxy.nginx.NginxRequestMetadataProvider, com.navercorp.pinpoint.agent.plugin.proxy.app.AppRequestMetadataProvider], org.apache.logging.log4j.spi.Provider=[org.apache.logging.log4j.core.impl.Log4jProvider], com.navercorp.pinpoint.profiler.context.recorder.proxy.ProxyRequestParserProvider=[com.navercorp.pinpoint.agent.plugin.proxy.app.AppRequestParserProvider, com.navercorp.pinpoint.agent.plugin.proxy.user.UserRequestParserProvider, com.navercorp.pinpoint.agent.plugin.proxy.apache.ApacheRequestParserProvider, com.navercorp.pinpoint.agent.plugin.proxy.nginx.NginxRequestParserProvider], org.apache.logging.log4j.util.PropertySource=[org.apache.logging.log4j.util.SystemPropertiesPropertySource, org.apache.logging.log4j.util.EnvironmentPropertySource], javax.annotation.processing.Processor=[org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor], org.apache.logging.log4j.core.util.ContextDataProvider=[org.apache.logging.log4j.core.impl.ThreadContextDataProvider], org.slf4j.spi.SLF4JServiceProvider=[org.apache.logging.slf4j.SLF4JServiceProvider], io.grpc.NameResolverProvider=[io.grpc.netty.UdsNameResolverProvider, io.grpc.internal.DnsNameResolverProvider], io.grpc.ManagedChannelProvider=[io.grpc.netty.UdsNettyChannelProvider, io.grpc.netty.NettyChannelProvider], reactor.blockhound.integration.BlockHoundIntegration=[io.netty.util.internal.Hidden$NettyBlockHoundIntegration], org.apache.commons.logging.LogFactory=[org.apache.logging.log4j.jcl.LogFactoryImpl], org.apache.logging.log4j.message.ThreadDumpMessage$ThreadInfoFactory=[org.apache.logging.log4j.core.message.ExtendedThreadInfoFactory]}
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleBuilder] defineModule module:module pinpoint.agent
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] com.navercorp.pinpoint.profiler.test package not found
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.instrument
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.management
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:jdk.management
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:jdk.unsupported
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.xml
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.desktop
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.logging
10-17 08:53:33.199 INFO  PinpointStarter                     : pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
10-17 08:53:33.203 INFO  Log4j2LoggingSystem                 : logPath:file:///pinpoint-agent/log4j2-agent.xml
10-17 08:53:33.392 WARN  PinpointStarter                     : pinpoint start failed.
com.navercorp.pinpoint.bootstrap.BootStrapException: execute fail. Error:null
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:51)
	at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:45)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:150)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.start(PinpointBootStrap.java:113)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:50)
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: com/lmax/disruptor/EventTranslatorVararg
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader.loadClass(Java9ClassLoader.java:111)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.async.AsyncLoggerContextSelector.createContext(AsyncLoggerContextSelector.java:46)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:230)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.LogManager.getContext(LogManager.java:289)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.logging.Log4j2LoggingSystem.getLoggerContext(Log4j2LoggingSystem.java:109)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.logging.Log4j2LoggingSystem.start(Log4j2LoggingSystem.java:48)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:72)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.lmax.disruptor.EventTranslatorVararg
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader.loadClass(Java9ClassLoader.java:124)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
```

**Comment by huijikim00** [comment]
It seems unrelated to the Java version.
Let me ask differently.
Looking at a log like "Caused by: java.lang.NoClassDefFoundError: com/lmax/disruptor/EventTranslatorVararg", it appears that an error is occurring due to a missing class/library.
Does the Pinpoint agent need to possess all the classes/libraries of the service being monitored?

**Comment by emeroad** [comment]
```
Caused by: java.lang.NoClassDefFoundError: com/lmax/disruptor/EventTranslatorVararg
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader.loadClass(Java9ClassLoader.java:111)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.core.async.AsyncLoggerContextSelector.createContext(AsyncLoggerContextSelector.java:46).
         //  AsyncLoggerContextSelector  <--- AsyncLogger ??
```
It looks like you have set up async logging in log4j-agent.xml.
I recommend removing the async config.
