### ISSUE TITLE
No serializer found for class com.navercorp.pinpoint.common.util.DelegateEnumeration

### ISSUE THREAD

**Issue by HiroC222** [pinpoint-apm/pinpoint#11695]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
2.5.3
jdk 1.8.0.212

#### Describe your problem**
An error is reported when the project runtime of the SpringBoot architecture is generated.
Is this a compatibility issue？

#### Logs
2024-11-08 12:54:15.648 | ERROR| http-nio-10201-exec-5 | controller:doBefore#92 | doBefore obj to json exception obj=org.apache.catalina.connector.RequestFacade@6876ef73,msg={}
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: **No serializer found for class com.navercorp.pinpoint.common.util.DelegateEnumeration** and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.apache.catalina.connector.RequestFacade["headerNames"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1277)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)

**Comment by emeroad** [comment]
Can you please post the reproduction code?

## Workaround
pinpoint.config
```
# Hide pinpoint headers.
profiler.tomcat.hidepinpointheader=true <<-- modify to disable
```

After modifying the above settings, pinpoint headers can be detected in tomcat header.

**Comment by HiroC222** [comment]
> Can you please post the reproduction code?
> 
> ## Workaround
> pinpoint.config
> 
> ```
> # Hide pinpoint headers.
> profiler.tomcat.hidepinpointheader=true <<-- modify to disable
> ```
> 
> After modifying the above settings, pinpoint headers can be detected in tomcat header.

thx I'll modify the config later, give it a try

**Comment by HiroC222** [comment]
It didn't work, here is my config

```
profiler.tomcat.hidepinpointheader=false
profiler.jetty.hidepinpointheader=true
profiler.jboss.hidepinpointheader=true
profiler.resin.hidepinpointheader=true
profiler.weblogic.hidepinpointheader=true
profiler.websphere.hidepinpointheader=true
profiler.vertx.http.server.hidepinpointheader=true
profiler.undertow.hidepinpointheader=true
```
