### ISSUE TITLE
Facing Grpc exceptions in collector logs for majority of the time with 2RC2 version - CANCELLED: call already cancelled and Received DATA frame for an unknown stream exceptions

### ISSUE THREAD

**Issue by dinesh4747** [pinpoint-apm/pinpoint#6504]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
V2.0-RC2

#### Describe the bug

Pre-dominantly facing two below exceptions from collector logs  - curious to understand what does signify to

a) call already cancelled exception -

2020-02-03 19:00:34 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Can not route stream data to consumer.(state:CONNECT_ARRIVED)
2020-02-03 19:00:35 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Can not route stream data to consumer.(state:CONNECT_ARRIVED)
2020-02-03 19:00:37 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Can not route stream data to consumer.(state:CONNECT_ARRIVED)
2020-02-03 19:00:38 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Can not route stream data to consumer.(state:CONNECT_ARRIVED)
04-Feb-2020 10:40:05.943 SEVERE [Pinpoint-GrpcAgent-Server-1] io.grpc.internal.SerializingExecutor.run Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@18634139
        io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
                at io.grpc.Status.asRuntimeException(Status.java:517)
                at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356)
                at com.navercorp.pinpoint.collector.receiver.grpc.PinpointGrpcServer.close(PinpointGrpcServer.java:289)
                at com.navercorp.pinpoint.collector.receiver.grpc.PinpointGrpcServer.disconnected(PinpointGrpcServer.java:273)
                at com.navercorp.pinpoint.collector.receiver.grpc.service.command.GrpcCommandService$2.onError(GrpcCommandService.java:131)
                at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:269)
                at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
                at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
                at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
                at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
                at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
                at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
                at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
                at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
                at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293)
                at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738)
                at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
                at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
04-Feb-2020 10:40:05.943 SEVERE [Pinpoint-GrpcAgent-Server-7] io.grpc.internal.SerializingExecutor.run Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@1e87c2fc
        io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
                at io.grpc.Status.asRuntimeException(Status.java:517)
                at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356)
                at com.navercorp.pinpoint.collector.receiver.grpc.PinpointGrpcServer.close(PinpointGrpcServer.java:289)
                at com.navercorp.pinpoint.collector.receiver.grpc.PinpointGrpcServer.disconnected(PinpointGrpcServer.java:273)
                at com.navercorp.pinpoint.collector.receiver.grpc.service.command.GrpcCommandService$2.onError(GrpcCommandService.java:131)
                at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:269)
                at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)

b) Stream Error - Received DATA frame for an unknown stream

020-02-13 08:50:43 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Can not route stream data to consumer.(state:CONNECT_ARRIVED)
2020-02-13 08:50:44 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Can not route stream data to consumer.(state:CONNECT_ARRIVED)
2020-02-13 08:50:44 [WARN ](c.n.p.c.c.ClusterPointRouter       ) handleStreamRouteCreate failed. command:TCmdActiveThreadCount(), routeResult:STREAM_CREATE_ERROR
13-Feb-2020 08:50:44.172 WARNING [Pinpoint-grpcAgentReceiver-Channel-Worker(8-5)] io.grpc.netty.NettyServerHandler.onStreamError Stream Error
        io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 23
                at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
                at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:591)
                at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:239)
                at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
                at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
                at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
                at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
                at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
                at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
                at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
                at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
                at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
13-Feb-2020 08:50:44.176 WARNING [Pinpoint-grpcAgentReceiver-Channel-Worker(8-2)] io.grpc.netty.NettyServerHandler.onStreamError Stream Error
#### What did you do to trigger the bug?

Steps to reproduce, for example:
1. All these logs are from single node collector logs

**Comment by emeroad** [comment]
@dinesh4747
Thank you for reporting

It seems to be a bug in grpc or netty.
We will investigate this issues.

**Comment by emeroad** [comment]
## Related issue
- https://github.com/grpc/grpc-java/issues/4651 
  Received DATA frame for an unknown stream error
- https://github.com/apache/skywalking/issues/1590 
  grpc bug
- https://github.com/netty/netty/pull/8028 
  Ignoring HEADER and DATA frames for streams that may hav…
- https://github.com/grpc/grpc-java/issues/3548
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream

**Comment by emeroad** [comment]
https://github.com/netty/netty/commit/cd9761b2fbee741a42f8cb205adfed3587195c4e#diff-179f52a9de82166ed577701a1412b5a0R591

**Comment by emeroad** [comment]
https://github.com/netty/netty/pull/9798
https://github.com/netty/netty/commit/09eed19438ca42eace467308aea72a707db7ea71

**Comment by emeroad** [comment]
I expect that the log will be reduced by Netty version upgrade.
Perhaps Netty version upgrade will not solve the problem.

I expect a problem with the resource capacity associated with API-META-DATA
 - thread-poll, queue size, etc

**Comment by dinesh4747** [comment]
@emeroad - Looks like this exceptions also resulted in issue https://github.com/naver/pinpoint/issues/6496  **API-METADATA-NOT-FOUND** 

As part of intermittent break-fix do you want me to increase couple of parameters in agent or collector, if yes could shed light here.
