### ISSUE TITLE
Pinpoint Agent with Java Web Start(JWS) application deployed in Weblogic

### ISSUE THREAD

**Issue by tarunve** [pinpoint-apm/pinpoint#7159]
Hi , 

I managed to install pinpoint successfully in my JWS application deployed on weblogic . 
Linux machine where weblogic is deployed is 32 bit using Java 6 (32 bit) JVM.

Below steps followed:
- Install Hbase on linux.
- Install Java 8 on linux.
- Run Collector , Web module with java 8.
- Attach agent to weblogic with below arguments:
`SAVE_JAVA_OPTIONS="${JAVA_OPTIONS} -javaagent:${HOME}/pinpoint/pinpoint-agent-2.0.4/pinpoint-bootstrap-2.0.4.jar -Dpinpoint.agentId=test-app-agent -Dpinpoint.applicationName=TEST-APP -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl"`

But now while launching my JWS application , it is giving me below error in Java console logs : 

```
java.lang.IllegalAccessError: superclass access check failed: class com.test.app.workspace.style.windows.WindowsLabelUI (in unnamed module @0x3f177e77) cannot access class com.sun.java.swing.plaf.windows.WindowsLabelUI (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x3f177e77
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at jdk.deploy@9.0.4/com.sun.deploy.security.DeployURLClassLoader.defineClass(Unknown Source)
	at jdk.deploy@9.0.4/com.sun.deploy.security.DeployURLClassLoader$1.run(Unknown Source)
	at jdk.deploy@9.0.4/com.sun.deploy.security.DeployURLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jdk.deploy@9.0.4/com.sun.deploy.security.DeployURLClassLoader.findClass(Unknown Source)
	at jdk.javaws@9.0.4/com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at jdk.javaws@9.0.4/com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(Unknown Source)
	at java.desktop/javax.swing.UIDefaults.getUIClass(Unknown Source)
	at java.desktop/javax.swing.UIDefaults.getUI(Unknown Source)
	at java.desktop/javax.swing.UIManager.getUI(Unknown Source)
	at java.desktop/javax.swing.JLabel.updateUI(Unknown Source)
	at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
	at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
	at com.test.app.workspace.ExceptionPane.<init>(ExceptionPane.java:177)
	at com.test.app.workspace.ExceptionPane.showExceptionDialog(ExceptionPane.java:428)
	at com.test.app.workspace.MDIWorkspace$34.run(MDIWorkspace.java:6183)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

I think it is happening to java versions. 
Can you please suggest , how to resolve it. I had to remove the agent to  start my application.

**Comment by emeroad** [comment]
Java Web Start is a client application. 
I don't know what this has to do with pinpoint.
Looking at the stack trace, there seems to be no pinpoint class.
Try using java 8 on the client pc

**Comment by tarunve** [comment]
Though it is web start application but server side is java only which is distributed between different clusters. 

I do have Java 8 installed on machine . But how to use - I mean where to use java 8 . Because in weblogic arguments , we are passing only the agent and which is running perfectly fine . So, what else to do ?
