### ISSUE TITLE
Pinpoint collector doesn't work

### ISSUE THREAD

**Issue by wmorgue** [pinpoint-apm/pinpoint#7206]
#### Prerequisites
👋 
I try to run the collector in the docker, but it doesn't work.

#### What version of pinpoint are you using?
master via docker

#### Describe your problem**

Follow the installation instructions from docker:
```
git clone https://github.com/naver/pinpoint-docker.git
cd pinpoint-docker
docker-compose pull && docker-compose up -d
```

#### What have you done?

1. I checked the status of the container with pinpoint-collector
2. See many error's

#### Logs
<details>
  <summary> docker logs pinpoint-collector</summary>
  
  ```bash
+ sed -i '/cluster.enable=/ s/=.*/=true/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-collector.properties
+ sed -i '/cluster.zookeeper.address=/ s/=.*/=/g' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-collector.properties
+ sed -i '/flink.cluster.enable=/ s/=.*/=true/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-collector.properties
+ sed -i '/flink.cluster.zookeeper.address=/ s/=.*/=pinpoint-hbase/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-collector.properties
+ sed -i '/hbase.client.host=/ s/=.*/=/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/profiles/release/hbase-env.properties
+ sed -i '/hbase.client.port=/ s/=.*/=/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/profiles/release/hbase-env.properties
+ sed -i '/level value=/ s/=.*/=""\/>/g' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/profiles/release/log4j.xml
+ exec /usr/local/tomcat/bin/catalina.sh run
02-Sep-2020 08:44:18.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.41
02-Sep-2020 08:44:18.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 4 2019 09:17:16 UTC
02-Sep-2020 08:44:18.296 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.41.0
02-Sep-2020 08:44:18.296 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Sep-2020 08:44:18.300 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-33-generic
02-Sep-2020 08:44:18.300 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Sep-2020 08:44:18.301 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
02-Sep-2020 08:44:18.301 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_212-8u212-b01-1~deb9u1-b01
02-Sep-2020 08:44:18.306 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
02-Sep-2020 08:44:18.306 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
02-Sep-2020 08:44:18.307 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
02-Sep-2020 08:44:18.307 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
02-Sep-2020 08:44:18.312 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Sep-2020 08:44:18.313 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dspring.profiles.active=release
02-Sep-2020 08:44:18.314 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Sep-2020 08:44:18.314 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Sep-2020 08:44:18.316 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
02-Sep-2020 08:44:18.316 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
02-Sep-2020 08:44:18.316 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
02-Sep-2020 08:44:18.320 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
02-Sep-2020 08:44:18.320 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
02-Sep-2020 08:44:18.321 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.5.2].
02-Sep-2020 08:44:18.324 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
02-Sep-2020 08:44:18.327 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
02-Sep-2020 08:44:18.349 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0j  20 Nov 2018]
02-Sep-2020 08:44:18.974 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-9080"]
02-Sep-2020 08:44:19.061 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
02-Sep-2020 08:44:19.148 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-9009"]
02-Sep-2020 08:44:19.166 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
02-Sep-2020 08:44:19.186 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 4818 ms
02-Sep-2020 08:44:19.355 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Sep-2020 08:44:19.356 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.41
02-Sep-2020 08:44:19.429 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
2020-09-02T08:44:50.396 PinpointCollectorApplicationInitializer::ActiveProfile:release
02-Sep-2020 08:44:51.076 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-09-02 08:45:10 [WARN ](o.a.h.u.NativeCodeLoader           ) Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-09-02 08:45:13 [WARN ](o.s.w.c.s.XmlWebApplicationContext ) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseAgentEventDao' defined in file [/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTemplate' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'hbaseTableFactory' while setting bean property 'tableFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTableFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'connectionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: java.lang.reflect.InvocationTargetException; nested exception is java.io.IOException: java.lang.reflect.InvocationTargetException
2020-09-02 08:45:13 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseAgentEventDao' defined in file [/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTemplate' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'hbaseTableFactory' while setting bean property 'tableFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTableFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'connectionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: java.lang.reflect.InvocationTargetException; nested exception is java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1135)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1869)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTemplate' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'hbaseTableFactory' while setting bean property 'tableFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTableFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'connectionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: java.lang.reflect.InvocationTargetException; nested exception is java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1534)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 28 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTableFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Cannot resolve reference to bean 'connectionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: java.lang.reflect.InvocationTargetException; nested exception is java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:145)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 42 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [applicationContext-collector-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: java.lang.reflect.InvocationTargetException; nested exception is java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1631)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 54 more
Caused by: com.navercorp.pinpoint.common.hbase.HbaseSystemException: java.lang.reflect.InvocationTargetException; nested exception is java.io.IOException: java.lang.reflect.InvocationTargetException
	at com.navercorp.pinpoint.common.hbase.ConnectionFactoryBean.afterPropertiesSet(ConnectionFactoryBean.java:79)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1689)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627)
	... 61 more
Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:150)
	at com.navercorp.pinpoint.common.hbase.ConnectionFactoryBean.afterPropertiesSet(ConnectionFactoryBean.java:76)
	... 63 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
	... 66 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.hadoop.conf.Configuration.getInt(Configuration.java:1104)
	at org.apache.hadoop.hbase.zookeeper.ZKConfig.getZKQuorumServersStringFromHbaseConfig(ZKConfig.java:306)
	at org.apache.hadoop.hbase.zookeeper.ZKConfig.getZKQuorumServersString(ZKConfig.java:328)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.<init>(ZooKeeperWatcher.java:178)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.<init>(ZooKeeperWatcher.java:153)
	at org.apache.hadoop.hbase.client.ZooKeeperKeepAliveConnection.<init>(ZooKeeperKeepAliveConnection.java:43)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getKeepAliveZooKeeperWatcher(ConnectionManager.java:1706)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:104)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:916)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:659)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:637)
	... 71 more
02-Sep-2020 08:45:13.772 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
02-Sep-2020 08:45:13.834 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
02-Sep-2020 08:45:14.018 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [54,582] ms
02-Sep-2020 08:45:14.049 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9080"]
02-Sep-2020 08:45:14.214 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-9009"]
02-Sep-2020 08:45:14.251 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 55063 ms
  ```
  
</details>

#### Additional context

```bash
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

Ubuntu 20.04 LTS
```

**Comment by minwoo-jung** [comment]
I think the hbase address setting is not working properly.
Check the pinpoint.zookeeper.address value in the properties file.

**Comment by wmorgue** [comment]
@minwoo-jung Thanks for reply.

In `.env`:
```
PINPOINT_VERSION=2.0.4
SPRING_PROFILES=release
#zookeeper information required
PINPOINT_ZOOKEEPER_ADDRESS=pinpoint-hbase
```

**Comment by wmorgue** [comment]
Upd.
Change `PINPOINT_ZOOKEEPER_ADDRESS` to `localhost` and got error's again.

**Comment by minwoo-jung** [comment]
Did you install hbase locally?

**Comment by wmorgue** [comment]
```bash
$ hadoop version
Hadoop 3.3.0
Source code repository https://gitbox.apache.org/repos/asf/hadoop.git -r aa96f1871bfd858f9bac59cf2a81ec470da649af
Compiled by brahma on 2020-07-06T18:44Z
Compiled with protoc 3.7.1
From source with checksum 5dc29b802d6ccd77b262ef9d04d19c4
This command was run using /usr/local/hadoop/share/hadoop/common/hadoop-common-3.3.0.jar
```
