### ISSUE TITLE
Log4j2 agent configuration file is incorrect

### ISSUE THREAD

**Issue by philippe-granet** [pinpoint-apm/pinpoint#7298]
#### What version of pinpoint are you using?
v2.1.0

#### Describe the bug
Log4j2 agent configuration file is incorrect

#### Logs
```
09-28 19:57:55.930 INFO  PinpointStarter                     : pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
09-28 19:57:55.940 INFO  Log4j2LoggingSystem                 : logPath:file:/pinpoint-agent/profiles/release/log4j2.xml
09-28 19:57:55.957 INFO  Log4j2LoggingSystem                 : patch ReflectionUtil codeSource:(file:/pinpoint-agent/lib/log4j-api-2.3.jar <no signer certificates>)
[Fatal Error] log4j2.xml:39:11: Le type d'�l�ment "Loggers" doit se terminer par la balise de fin correspondante "</Loggers>".
ERROR StatusLogger Error parsing /pinpoint-agent/profiles/release/log4j2.xml org.xml.sax.SAXParseException; systemId: file:///pinpoint-agent/profiles/release/log4j2.xml; lineNumber: 39; columnNumber: 11; Le type d'�l�ment "Loggers" doit se terminer par la balise de fin correspondante "</Loggers>".
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:140)
        at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:44)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:233)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:426)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:202)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:249)
        at com.navercorp.pinpoint.profiler.logging.Log4j2LoggingSystem.getLoggerContext(Log4j2LoggingSystem.java:84)
        at com.navercorp.pinpoint.profiler.logging.Log4j2LoggingSystem.start(Log4j2LoggingSystem.java:43)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:68)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:53)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:48)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:132)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
```

**Comment by philippe-granet** [comment]
Problem seems to be in /pinpoint-agent/profiles/release/log4j2.xml , there is a `/` after root level:
```
        <Root level="INFO"/>
            <AppenderRef ref="console"/>
            <AppenderRef ref="rollingFile"/>
        </Root>
```
Bug in https://github.com/naver/pinpoint-docker/blob/master/pinpoint-agent/build/scripts/configure-agent.sh#L21 ?
`sed -i "/Root level=/ s/=.*/=\"${DEBUG_LEVEL}\"\/>/g" /pinpoint-agent/profiles/${SPRING_PROFILES}/log4j2.xml`

**Comment by RoySRose** [comment]
Hello, @philippe-granet 

Yes, you're right there was an unintended character added to the script.

I've just updated rebuilt the image on dockerhub.
