### ISSUE TITLE
agentID and agentName  I want to use more than 24 characters.Could you tell me where to fix it?

### ISSUE THREAD

**Issue by tobewithyou1996** [pinpoint-apm/pinpoint#7389]
agentID and agentName  I want to use more than 24 characters.Could you tell me where to fix it?  I try to use this method to come from https://github.com/pinpoint-apm/pinpoint/pull/6015/commits/29ab391de758336900256ef0ce24d806e3a1eab5 ， but have some error:

From collector
``` 
11-09 06:02:49.049 [cAgent-Server-7] INFO  c.n.p.g.s.HeaderPropagationInterceptor   : Header extract fail cause=INVALID_ARGUMENT: invalid agentid, method=v1.ProfilerCommandService/HandleCommandV2 headers=Metadata(content-type=application/grpc,user-agent=grpc-java-netty/1.14.0,supportcommandcode=740;710;730;750,agentid=yy-test-1234567890-1234567890,applicationname=yy-djxd-1234567890-1234567890,starttime=1604901564349,grpc-accept-encoding=gzip), attr={remote-addr=/172.19.0.1:49256, transportMetadata=DefaultTransportMetadata{debugString='grpcAgentReceiver', remoteAddress=/172.19.0.1:49256, transportId=6, connectTime=1604901567545}}
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid agentid
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.14.0.jar!/:1.14.0]
	at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.validateId(AgentHeaderReader.java:110) ~[pinpoint-grpc-2.1.0.jar!/:2.1.0]
	at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.getId(AgentHeaderReader.java:68) ~[pinpoint-grpc-2.1.0.jar!/:2.1.0]
	at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.extract(AgentHeaderReader.java:41) ~[pinpoint-grpc-2.1.0.jar!/:2.1.0]
	at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.extract(AgentHeaderReader.java:34) ~[pinpoint-grpc-2.1.0.jar!/:2.1.0]
	at com.navercorp.pinpoint.grpc.server.HeaderPropagationInterceptor.interceptCall(HeaderPropagationInterceptor.java:55) [pinpoint-grpc-2.1.0.jar!/:2.1.0]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229) [grpc-core-1.14.0.jar!/:1.14.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:560) [grpc-core-1.14.0.jar!/:1.14.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:541) [grpc-core-1.14.0.jar!/:1.14.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1800(ServerImpl.java:361) [grpc-core-1.14.0.jar!/:1.14.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:477) [grpc-core-1.14.0.jar!/:1.14.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar!/:1.14.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar!/:1.14.0]
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:109) [classes!/:2.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

From agent

```
11-09 14:24:26.026 [-Executor(14-0)] WARN  c.n.p.p.s.g.ResponseStreamObserver       -- Failed to stream, name=StatStream-4486, cause=INVALID_ARGUMENT: INVALID_ARGUMENT: invalid agentid
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: INVALID_ARGUMENT: invalid agentid
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420) [grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.14.0.jar:2.1.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.14.0.jar:2.1.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.14.0.jar:2.1.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.14.0.jar:2.1.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) [grpc-core-1.14.0.jar:2.1.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar:2.1.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar:2.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

**Comment by HyunjoonCho** [comment]
Maybe those constants? I didn't try it though
<https://github.com/pinpoint-apm/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/PinpointConstants.java>

**Comment by tobewithyou1996** [comment]
thank you, use  https://github.com/pinpoint-apm/pinpoint/commit/29ab391de758336900256ef0ce24d806e3a1eab5 is ok.
