### ISSUE TITLE
schema not equals.

### ISSUE THREAD

**Issue by vic-kjs** [pinpoint-apm/pinpoint#7768]
**on pinpoint web
This error occurs only in a specific application.
I am curious about a solution.**

    java.lang.IllegalArgumentException: schema not equals. this=TimeHistogram{​​​​​​​timeStamp=1617182340000, Histogram{​​​​​​​schema={​​​​​​​typeCode=1, fastSlot=HistogramSlot{​​​​​​​slotTime=100, slotType=FAST, slotName='100ms'}​​​​​​​, normalSlot=HistogramSlot{​​​​​​​slotTime=300, slotType=NORMAL, slotName='300ms'}​​​​​​​, slowSlot=HistogramSlot{​​​​​​​slotTime=500, slotType=SLOW, slotName='500ms'}​​​​​​​, verySlowSlot=HistogramSlot{​​​​​​​slotTime=0, slotType=VERY_SLOW, slotName='Slow'}​​​​​​​, errorSlot=HistogramSlot{​​​​​​​slotTime=-1, slotType=ERROR, slotName='Error'}​​​​​​​, fastErrorSlot=HistogramSlot{​​​​​​​slotTime=-100, slotType=FAST_ERROR, slotName='100ms'}​​​​​​​, normalErrorSlot=HistogramSlot{​​​​​​​slotTime=-300, slotType=NORMAL_ERROR, slotName='300ms'}​​​​​​​, slowErrorSlot=HistogramSlot{​​​​​​​slotTime=-500, slotType=SLOW_ERROR, slotName='500ms'}​​​​​​​, verySlowErrorSlot=HistogramSlot{​​​​​​​slotTime=-999, slotType=VERY_SLOW_ERROR, slotName='Slow'}​​​​​​​}​​​​​​​, fastCount=0, normalCount=0, slowCount=0, verySlowCount=0, errorCount=0, fastErrorCount=0, normalErrorCount=0, slowErrorCount=0, verySlowErrorCount=0}​​​​​​​}​​​​​​​, histogram=TimeHistogram{​​​​​​​timeStamp=1617182340000, Histogram{​​​​​​​schema={​​​​​​​typeCode=2, fastSlot=HistogramSlot{​​​​​​​slotTime=1000, slotType=FAST, slotName='1s'}​​​​​​​, normalSlot=HistogramSlot{​​​​​​​slotTime=3000, slotType=NORMAL, slotName='3s'}​​​​​​​, slowSlot=HistogramSlot{​​​​​​​slotTime=5000, slotType=SLOW, slotName='5s'}​​​​​​​, verySlowSlot=HistogramSlot{​​​​​​​slotTime=0, slotType=VERY_SLOW, slotName='Slow'}​​​​​​​, errorSlot=HistogramSlot{​​​​​​​slotTime=-1, slotType=ERROR, slotName='Error'}​​​​​​​, fastErrorSlot=HistogramSlot{​​​​​​​slotTime=-1000, slotType=FAST_ERROR, slotName='1s'}​​​​​​​, normalErrorSlot=HistogramSlot{​​​​​​​slotTime=-3000, slotType=NORMAL_ERROR, slotName='3s'}​​​​​​​, slowErrorSlot=HistogramSlot{​​​​​​​slotTime=-5000, slotType=SLOW_ERROR, slotName='5s'}​​​​​​​, verySlowErrorSlot=HistogramSlot{​​​​​​​slotTime=-9999, slotType=VERY_SLOW_ERROR, slotName='Slow'}​​​​​​​}​​​​​​​, fastCount=1, normalCount=0, slowCount=0, verySlowCount=0, errorCount=0, fastErrorCount=0, normalErrorCount=0, slowErrorCount=0, verySlowErrorCount=0}​​​​​​​}​​​​​​​
    at com.navercorp.pinpoint.web.applicationmap.histogram.Histogram.add(Histogram.java:201)
    at com.navercorp.pinpoint.web.applicationmap.rawdata.LinkCallData.addCallData(LinkCallData.java:89)
    at com.navercorp.pinpoint.web.applicationmap.rawdata.LinkCallDataMap.addCallData(LinkCallDataMap.java:54)
    at com.navercorp.pinpoint.web.service.map.VirtualLinkHandler.fillEmulationLink(VirtualLinkHandler.java:147)
    at com.navercorp.pinpoint.web.service.map.VirtualLinkHandler.processVirtualLinks(VirtualLinkHandler.java:73)
    at com.navercorp.pinpoint.web.service.map.UnidirectionalLinkSelector.select(UnidirectionalLinkSelector.java:89)
    at com.navercorp.pinpoint.web.service.MapServiceImpl.selectApplicationMap(MapServiceImpl.java:109)
    at com.navercorp.pinpoint.web.controller.MapController.selectApplicationMap(MapController.java:218)
    at com.navercorp.pinpoint.web.controller.MapController.getServerMapDataV2(MapController.java:202)
    at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at com.navercorp.pinpoint.web.servlet.NoCacheFilter.doFilter(NoCacheFilter.java:50)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at com.navercorp.pinpoint.web.servlet.RewriteForV2Filter.doFilter(RewriteForV2Filter.java:91)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
 

#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

**Comment by emeroad** [comment]
Could you please tell me how to reproduce it?

**Comment by vic-kjs** [comment]
After changing the settings below to the initial values, the problem was solved.
profiler.kafka.producer.enable=true
profiler.springkafka.consumer.enable=true

I changed the settings a long time ago, but the problem occurred recently. 
No changes were confirmed on the target system.

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#compatibility
Please check the compatibility table.

It may be a compatibility problem between the agent and the collector.
