### ISSUE TITLE
RequestRejectedException

### ISSUE THREAD

**Issue by ga-ram** [pinpoint-apm/pinpoint#7975]
#### What version of pinpoint are you using?
master

#### Describe the bug
RequestRejectedException occurs in certain environment after updating spring security version from 5.3.6 to 5.4.6.
Although it does not occur all the time, temporary workaround to allow all header values in Spring HttpFirewall might be useful. 

06-16 18:44:22.022 [nio-9000-exec-3] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet]      -- Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.socket.server.HandshakeFailureException: Uncaught failure for request http://pinpoint.navercorp.com/agent/activeThread.pinpointws; nested exception is org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the header value "ì<86>¡í<98><9c>ì§<84>" is not allowed.] with root cause
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the header value "ì<86>¡í<98><9c>ì§<84>" is not allowed.
        at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.validateAllowedHeaderValue(StrictHttpFirewall.java:739) ~[spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.access$000(StrictHttpFirewall.java:605) ~[spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1.nextElement(StrictHttpFirewall.java:647) ~[spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1.nextElement(StrictHttpFirewall.java:637) ~[spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1.nextElement(StrictHttpFirewall.java:646) ~[spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1.nextElement(StrictHttpFirewall.java:637) ~[spring-security-web-5.4.6.jar!/:5.4.6]

**Comment by yjqg6666** [comment]
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the header value "ì<86>¡í<98><9c>ì§<84>" is not allowed.

**Comment by ga-ram** [comment]
This happens when ServerHttpRequest.getHeaders() tries to validate all headers (even the ones I don't use) via spring-projects/spring-security#8644, and it seems like the custom nginx filter puts korean characters into the header value. 

Since I found the source of these weird characters, this commit is not needed, thereby closing this issue.

**Comment by yjqg6666** [comment]
@ga-ram Thanks for the further info link.
