### ISSUE TITLE
Pinpoint Collector fails

### ISSUE THREAD

**Issue by vikasthakur99** [pinpoint-apm/pinpoint#8013]
#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v2.2.2

#### Describe your problem**
I installed pinpoint on RHEL-7
Java 7,8,9 are installed.
executed - ./mvnw install -DskipTests=true and  it was successful.

Then as per instructions, executed following to start the collector:

java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.3.0-SNAPSHOT.jar

And I could see multiple errors on screen.

#### What have you done?
Steps you have taken to trigger the problem, for example:
I executed following to start the collector:

java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.3.0-SNAPSHOT.jar

#### Logs
07-07 17:54:08.008 [localhost:2181)] WARN  o.a.h.h.s.o.a.z.ClientCnxn               : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) [hbase-shaded-client-1.4.13.jar!/:1.4.13]
07-07 17:54:08.008 [localhost:2181)] INFO  o.a.h.h.s.o.a.z.ClientCnxn               : Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SA
SL (unknown error)
07-07 17:54:08.008 [localhost:2181)] WARN  o.a.h.h.s.o.a.z.ClientCnxn               : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) [hbase-shaded-client-1.4.13.jar!/:1.4.13]
07-07 17:54:08.008 [localhost:2181)] INFO  o.a.z.ClientCnxn                         : Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SA
SL (unknown error)
07-07 17:54:08.008 [localhost:2181)] INFO  o.a.z.ClientCnxn                         : Socket error occurred: localhost/127.0.0.1:2181: Connection refused
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.r.ExecutorFactoryBean            : Shutting down ExecutorService 'grpcAgentServerExecutor'
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.r.g.s.c.GrpcCommandService       : close() started
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.z.ZookeeperClusterService      : ZookeeperClusterService destroying started.
07-07 17:54:08.008 [extShutdownHook] INFO  .p.c.c.z.ZookeeperProfilerClusterManager : stop() started.
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.z.ZookeeperJobWorker           : stop() started.
07-07 17:54:08.008 [rJobWorker(2-0)] INFO  c.n.p.c.c.z.ZookeeperJobWorker           : run() completed.
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.z.ZookeeperJobWorker           : stop() completed.
07-07 17:54:08.008 [extShutdownHook] INFO  .p.c.c.z.ZookeeperProfilerClusterManager : stop() completed.
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.z.ZookeeperClusterManager      : ZookeeperClusterManager destroying started.
07-07 17:54:08.008 [extShutdownHook] INFO  .c.c.c.CollectorClusterConnectionManager : CollectorClusterConnectionManager destroying started.
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.c.CollectorClusterConnector    : CollectorClusterConnector destroying started.
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.c.CollectorClusterConnector    : CollectorClusterConnector destroying completed.
07-07 17:54:08.008 [extShutdownHook] INFO  .c.c.c.CollectorClusterConnectionManager : CollectorClusterConnectionManager destroying completed.
07-07 17:54:08.008 [terManager(3-0)] INFO  c.n.p.c.c.z.ZookeeperClusterManager      : Worker stopped
07-07 17:54:08.008 [extShutdownHook] INFO  c.n.p.c.c.z.ZookeeperClusterManager      : ZookeeperClusterManager destroying completed.
07-07 17:54:08.008 [tor-Framework-0] INFO  o.a.c.f.i.CuratorFrameworkImpl           : backgroundOperationsLoop exiting
07-07 17:54:09.009 [localhost:2181)] INFO  o.a.h.h.s.o.a.z.ClientCnxn               : Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
07-07 17:54:09.009 [localhost:2181)] WARN  o.a.h.h.s.o.a.z.ClientCnxn               : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]

**Comment by koo-taejin** [comment]
Hi @vikasthakur99 

Error logs show it has problem with connecting Zookeeper. 
Please check whether Zookeeper works well or not. 


Thanks :)
