### ISSUE TITLE
ServerMap Drawing not working properly after 2.3.0

### ISSUE THREAD

**Issue by dv-morais** [pinpoint-apm/pinpoint#8063]
Hello,

I just have updated to version 2.3.0 and I found myself with the problem below

![image](https://user-images.githubusercontent.com/57958197/126710784-d303fb52-b7ca-4b93-b50f-ce6db43275db.png)

I did clone the repository and built from source....

is something wrong that I need to take care of?

**Comment by emeroad** [comment]
We do not reproduce this problem.
Can you provide information on how the problem is reproduced?

**Comment by dv-morais** [comment]
1. git clone --branch v2.3.0 https://github.com/pinpoint-apm/pinpoint.git
2. ./mvnw clean install -DskipTests=true

moved the content inside the "deploy" folder and have executed it.

hbase version= 2.3.0

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#compatibility
Check the HBase compatibility table.

**Comment by dv-morais** [comment]
I see... looks like I was distracted :D

thanks for clarification!

**Comment by dv-morais** [comment]
I mean... I'm supposed to continue building using that workround? 

-Dhbase.shaded.client.version=2.1.1

**Comment by dv-morais** [comment]
Now I'm facing this.

java -jar pinpoint-hbase2-collector-boot-2.3.0.jar

Exception in thread "main" java.lang.ClassNotFoundException: com.navercorp.pinpoint.collector.Hbase2CollectorApp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
