### ISSUE TITLE
setup flink job error

### ISSUE THREAD

**Issue by urlence** [pinpoint-apm/pinpoint#8080]
**What version of pinpoint are you using?**
pinpoint: v2.2.2
flink: v1.13.1

**Describe your problem**
I set env in flink-conf.yaml
env.java.opts: -Dspring.profiles.active=local -Dflink.StreamExecutionEnvironment=server
But I'm getting an error like this `Failed to execute job 'Aggregation Stat Data'.`

**log**

`./bin/flink run ../pinpoint-flink-job-2.2.2.jar`

`2021-07-27 06:54:33,334 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper       [] - Process identifier=hconnection-0x5b43e173 connecting to ZooKeeper ensemble=localhost:2181
2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:host.name=<NA>
2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.version=1.8.0_252
2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.vendor=Azul Systems, Inc.
2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.home=/usr/lib/jvm/zulu-8/jre
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.class.path=/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-csv-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-json-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-shaded-zookeeper-3.4.14.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-table-blink_2.11-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-table_2.11-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-1.2-api-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-api-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-core-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-slf4j-impl-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-dist_2.11-1.13.1.jar::::/home/ww/pinpoint/hbase-1.2.7/conf
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.io.tmpdir=/tmp
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.compiler=<NA>
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:os.name=Linux
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:os.arch=amd64
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:os.version=3.10.0-327.el7.x86_64
2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:user.name=ww
2021-07-27 06:54:33,344 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:user.home=/home/ww
2021-07-27 06:54:33,346 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:user.dir=/home/ww/pinpoint/flink/flink-1.13.1
2021-07-27 06:54:33,347 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=org.apache.hadoop.hbase.zookeeper.PendingWatcher@7ba63fe5
2021-07-27 06:54:33,362 WARN  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/tmp/jaas-9051868129661544506.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it.
2021-07-27 06:54:33,365 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - Opening socket connection to server localhost/127.0.0.1:2181
2021-07-27 06:54:33,399 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2021-07-27 06:54:33,430 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x17a5fb7441c0059, negotiated timeout = 40000

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Failed to execute job 'Aggregation Stat Data'.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: org.apache.flink.util.FlinkException: Failed to execute job 'Aggregation Stat Data'.
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:1970)
	at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:135)
	at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:76)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1834)
	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.start(StatStreamingVer2Job.java:153)
	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.main(StatStreamingVer2Job.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 8 more
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
	at org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:316)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedFunction$2(FunctionUtils.java:75)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
	at org.apache.flink.runtime.jobmaster.DefaultJobMasterServiceProcess.lambda$new$0(DefaultJobMasterServiceProcess.java:97)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Window(TumblingEventTimeWindows(10000), EventTimeTrigger, ApplicationStatBoWindow) -> Sink: Unnamed': Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	... 7 more
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Window(TumblingEventTimeWindows(10000), EventTimeTrigger, ApplicationStatBoWindow) -> Sink: Unnamed': Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
	at org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:316)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:114)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 7 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Window(TumblingEventTimeWindows(10000), EventTimeTrigger, ApplicationStatBoWindow) -> Sink: Unnamed': Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraphBuilder.buildGraph(DefaultExecutionGraphBuilder.java:178)
	at org.apache.flink.runtime.scheduler.DefaultExecutionGraphFactory.createAndRestoreExecutionGraph(DefaultExecutionGraphFactory.java:107)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:342)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:190)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:120)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:132)
	at org.apache.flink.runtime.jobmaster.DefaultSlotPoolServiceSchedulerFactory.createScheduler(DefaultSlotPoolServiceSchedulerFactory.java:110)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:340)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:317)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.internalCreateJobMasterService(DefaultJobMasterServiceFactory.java:107)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.lambda$createJobMasterService$0(DefaultJobMasterServiceFactory.java:95)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:112)
	... 8 more
Caused by: java.lang.Exception: Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:105)
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraphBuilder.buildGraph(DefaultExecutionGraphBuilder.java:174)
	... 19 more
Caused by: java.lang.IllegalStateException: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
	at org.apache.flink.api.common.io.RichOutputFormat.getRuntimeContext(RichOutputFormat.java:47)
	at com.navercorp.pinpoint.flink.dao.hbase.StatisticsDao.configure(StatisticsDao.java:56)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:99)
	... 20 more
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/hadoop/util/ShutdownHookManager$2
	at org.apache.hadoop.util.ShutdownHookManager.getShutdownHooksInOrder(ShutdownHookManager.java:124)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.ShutdownHookManager$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more`

**Comment by emeroad** [comment]
Could you check the pinpoint-flink-job-2.2.2.jar?

![image](https://user-images.githubusercontent.com/7564547/128487722-23bed716-623c-494b-94bc-5eaf4db2d9f5.png)
https://github.com/pinpoint-apm/pinpoint/releases/tag/v2.2.2
There seems to be no problem with Assets.

**Comment by kartikzheng** [comment]
> **What version of pinpoint are you using?** pinpoint: v2.2.2 flink: v1.13.1
> 
> **Describe your problem** I set env in `flink-conf.yaml` `env.java.opts: -Dspring.profiles.active=local -Dflink.StreamExecutionEnvironment=server` But I'm getting an error like this `Failed to execute job 'Aggregation Stat Data'.`
> 
> **log**
> 
> `./bin/flink run ../pinpoint-flink-job-2.2.2.jar`
> 
> ```
> 2021-07-27 06:54:33,334 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper       [] - Process identifier=hconnection-0x5b43e173 connecting to ZooKeeper ensemble=localhost:2181
> 2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
> 2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:host.name=<NA>
> 2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.version=1.8.0_252
> 2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.vendor=Azul Systems, Inc.
> 2021-07-27 06:54:33,342 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.home=/usr/lib/jvm/zulu-8/jre
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.class.path=/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-csv-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-json-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-shaded-zookeeper-3.4.14.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-table-blink_2.11-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-table_2.11-1.13.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-1.2-api-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-api-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-core-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/log4j-slf4j-impl-2.12.1.jar:/home/ww/pinpoint/flink/flink-1.13.1/lib/flink-dist_2.11-1.13.1.jar::::/home/ww/pinpoint/hbase-1.2.7/conf
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.io.tmpdir=/tmp
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:java.compiler=<NA>
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:os.name=Linux
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:os.arch=amd64
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:os.version=3.10.0-327.el7.x86_64
> 2021-07-27 06:54:33,343 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:user.name=ww
> 2021-07-27 06:54:33,344 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:user.home=/home/ww
> 2021-07-27 06:54:33,346 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Client environment:user.dir=/home/ww/pinpoint/flink/flink-1.13.1
> 2021-07-27 06:54:33,347 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper [] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=org.apache.hadoop.hbase.zookeeper.PendingWatcher@7ba63fe5
> 2021-07-27 06:54:33,362 WARN  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/tmp/jaas-9051868129661544506.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it.
> 2021-07-27 06:54:33,365 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - Opening socket connection to server localhost/127.0.0.1:2181
> 2021-07-27 06:54:33,399 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - Socket connection established to localhost/127.0.0.1:2181, initiating session
> 2021-07-27 06:54:33,430 INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn [] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x17a5fb7441c0059, negotiated timeout = 40000
> 
> ------------------------------------------------------------
>  The program finished with the following exception:
> 
> org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Failed to execute job 'Aggregation Stat Data'.
> 	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
> 	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
> 	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
> 	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
> 	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
> 	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
> 	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
> 	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
> 	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
> Caused by: org.apache.flink.util.FlinkException: Failed to execute job 'Aggregation Stat Data'.
> 	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:1970)
> 	at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:135)
> 	at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:76)
> 	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1834)
> 	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.start(StatStreamingVer2Job.java:153)
> 	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.main(StatStreamingVer2Job.java:48)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
> 	... 8 more
> Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
> 	at org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:316)
> 	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedFunction$2(FunctionUtils.java:75)
> 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
> 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
> 	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
> 	at org.apache.flink.runtime.jobmaster.DefaultJobMasterServiceProcess.lambda$new$0(DefaultJobMasterServiceProcess.java:97)
> 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
> 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Window(TumblingEventTimeWindows(10000), EventTimeTrigger, ApplicationStatBoWindow) -> Sink: Unnamed': Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
> 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
> 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
> 	... 7 more
> Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Window(TumblingEventTimeWindows(10000), EventTimeTrigger, ApplicationStatBoWindow) -> Sink: Unnamed': Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
> 	at org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:316)
> 	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:114)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
> 	... 7 more
> Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Window(TumblingEventTimeWindows(10000), EventTimeTrigger, ApplicationStatBoWindow) -> Sink: Unnamed': Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
> 	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraphBuilder.buildGraph(DefaultExecutionGraphBuilder.java:178)
> 	at org.apache.flink.runtime.scheduler.DefaultExecutionGraphFactory.createAndRestoreExecutionGraph(DefaultExecutionGraphFactory.java:107)
> 	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:342)
> 	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:190)
> 	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:120)
> 	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:132)
> 	at org.apache.flink.runtime.jobmaster.DefaultSlotPoolServiceSchedulerFactory.createScheduler(DefaultSlotPoolServiceSchedulerFactory.java:110)
> 	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:340)
> 	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:317)
> 	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.internalCreateJobMasterService(DefaultJobMasterServiceFactory.java:107)
> 	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.lambda$createJobMasterService$0(DefaultJobMasterServiceFactory.java:95)
> 	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:112)
> 	... 8 more
> Caused by: java.lang.Exception: Configuring the output format (null) failed: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
> 	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:105)
> 	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraphBuilder.buildGraph(DefaultExecutionGraphBuilder.java:174)
> 	... 19 more
> Caused by: java.lang.IllegalStateException: The runtime context has not been initialized yet. Try accessing it in one of the other life cycle methods.
> 	at org.apache.flink.api.common.io.RichOutputFormat.getRuntimeContext(RichOutputFormat.java:47)
> 	at com.navercorp.pinpoint.flink.dao.hbase.StatisticsDao.configure(StatisticsDao.java:56)
> 	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:99)
> 	... 20 more
> Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/hadoop/util/ShutdownHookManager$2
> 	at org.apache.hadoop.util.ShutdownHookManager.getShutdownHooksInOrder(ShutdownHookManager.java:124)
> 	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:52)
> Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.ShutdownHookManager$2
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
> 	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
> 	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 2 more
> ```

I have the same problem. Have you solved it？
