### ISSUE TITLE
JBOSS Pinpoint onboarding - Getting exception for ojdbc8.jar deployment while server startup

### ISSUE THREAD

**Issue by VishalShahare** [pinpoint-apm/pinpoint#8111]
we have below deployments in domain.xml :
.
.
.

  </jvm>
            <socket-binding-group ref="full-ha-sockets"/>
            <deployments>
                <deployment name="ojdbc8.jar" runtime-name="ojdbc8.jar"/>
                <deployment name="wpServerPlus.ear" runtime-name="wpServerPlus.ear"/>
                <deployment name="workListHandler.war" runtime-name="workListHandler.war"/>
            </deployments>
        </server-group>

while pinpoint onboarding (2.2.2) we are getting below exception for deployment.ojdbc8.jar

[0m08-12 20:08:07.007 [read Pool -- 81] ERROR c.n.p.p.t.BaseClassFileTransformer       -- Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:vfs:/content/ojdbc8.jar cl:ModuleClassLoader for Module "deployment.ojdbc8.jar" from Service Module Loader ctxCl:ModuleClassLoader for Module "deployment.ojdbc8.jar" from Service Module Loader agentCl:ParallelClassLoader@1995265320{name='pinpoint.agent'} Cause:/content/ojdbc8.jar create fail
java.lang.IllegalStateException: /content/ojdbc8.jar create fail
	at com.navercorp.pinpoint.profiler.instrument.scanner.JarFileScanner.<init>(JarFileScanner.java:38) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.profiler.instrument.scanner.ClassScannerFactory.newURLScanner(ClassScannerFactory.java:81) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.profiler.instrument.scanner.ClassScannerFactory.newScanner(ClassScannerFactory.java:46) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.exist(PluginInstrumentContext.java:89) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.profiler.instrument.GuardInstrumentor.exist(GuardInstrumentor.java:64) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.plugin.jdbc.oracle.OraclePlugin$StatementTransformer.doInTransform(OraclePlugin.java:268) ~[?:?]
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:66) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.profiler.transformer.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at com.navercorp.pinpoint.profiler.transformer.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:87) ~[pinpoint-profiler-2.2.2.jar:2.2.2]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) ~[?:1.8.0_121]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:839) ~[?:1.8.0_121]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424) ~[?:?]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555) ~[?:?]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339) ~[?:?]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126) ~[?:?]
	at org.jboss.modules.Module.loadModuleClass(Module.java:731) ~[?:?]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398) ~[?:?]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:601) ~[ojdbc8.jar:12.2.0.1.0]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:321) ~[?:?]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352) ~[?:?]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.access$200(LocalManagedConnectionFactory.java:62) ~[?:?]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory$1$1.run(LocalManagedConnectionFactory.java:259) ~[?:?]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory$1$1.run(LocalManagedConnectionFactory.java:250) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_121]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory$1.run(LocalManagedConnectionFactory.java:249) ~[?:?]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory$1.run(LocalManagedConnectionFactory.java:246) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:245) ~[?:?]
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1326) ~[?:?]
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:499) ~[?:?]
	at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632) ~[?:?]
	at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604) ~[?:?]
	at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624) ~[?:?]
	at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:440) ~[?:?]
	at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789) ~[?:?]
	at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:151) ~[?:?]
	at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64) ~[?:?]
	at com.amdocs.kenanfx.qps.dao.JdbcUtil.getDSConnection(Unknown Source) ~[?:?]
	at com.amdocs.kenanfx.qps.process.QpsContextContainer.getProcessSockets(Unknown Source) ~[?:?]
	at com.amdocs.kenanfx.qps.process.QpsContextContainer.Init(Unknown Source) ~[?:?]
	at com.amdocs.kenanfx.qps.ws.servlet.StartupServlet.init(Unknown Source) ~[?:?]
	at javax.servlet.GenericServlet.init(GenericServlet.java:180) ~[jboss-servlet-api_4.0_spec-2.0.0.Final-redhat-00001.jar!/:2.0.0.Final-redhat-00001]
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78) ~[?:?]
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:585) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541) ~[?:?]
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598) [undertow-servlet-2.0.30.SP3-redhat-00001.jar!/:2.0.30.SP3-redhat-00001]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97) [wildfly-undertow-7.3.1.GA-redhat-00003.jar!/:7.3.1.GA-redhat-00003]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78) [wildfly-undertow-7.3.1.GA-redhat-00003.jar!/:7.3.1.GA-redhat-00003]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final-redhat-00001.jar!/:2.3.3.Final-redhat-00001]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final-redhat-00001.jar!/:2.3.3.Final-redhat-00001]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final-redhat-00001.jar!/:2.3.3.Final-redhat-00001]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.3.Final-redhat-00001.jar!/:2.3.3.Final-redhat-00001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
	at org.jboss.threads.JBossThread.run(JBossThread.java:485) [jboss-threads-2.3.3.Final-redhat-00001.jar!/:2.3.3.Final-redhat-00001]

**Comment by emeroad** [comment]
```
/content/ojdbc8.jar
```

It seems that pinpoint does not correctly recognize the location of the jar file.
Could you tell me how to reproduce it?

**Comment by VishalShahare** [comment]
to reproduce this issue please add odbc.jar in deployment section of domain.xml for JBOSS...
<server-groups>
        <server-group name="fxapi-stream" profile="full-ha">
            <jvm name="default">
                <heap size="1024m" max-size="4096m"/>
                <permgen max-size="512m"/>
                <jvm-options>
                    <option value="-server"/>
                    <option value="-XX:+UseG1GC"/>
                    <option value="-XX:+UseStringDeduplication"/>
                    <option value="-XX:MetaspaceSize=1024m"/>
                    <option value="-XX:MaxMetaspaceSize=2048m"/>
                    <option value="-Xbootclasspath/p:/{ path to jar file }/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.1.14.Final-redhat-00001.jar"/>
                    <option value="-Xbootclasspath/p:/{ path to jar file }/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.5.1.Final-redhat-00001.jar"/>
                    <option value="-javaagent:/{ path to jar file }/pinpointagent222/pinpoint-bootstrap-2.2.2.jar"/>
                    <option value="-Dpinpoint.applicationName=XYZ"/>
                </jvm-options>
            </jvm>
            <socket-binding-group ref="full-ha-sockets"/>
            <deployments>
                <deployment name="ojdbc8.jar" runtime-name="ojdbc8.jar"/>
                <deployment name="XYZ.ear" runtime-name="XYZ.ear"/>
            </deployments>

**Comment by VishalShahare** [comment]
[Domain_Sample.txt](https://github.com/pinpoint-apm/pinpoint/files/6981181/Domain_Sample.txt)
