### ISSUE TITLE
JBOSS PINPOINT onboarding - need to add addition - -Xbootclasspath along with mentioned parameters in pinpoint document

### ISSUE THREAD

**Issue by VishalShahare** [pinpoint-apm/pinpoint#8112]
we observed below exception while Pinpoint onboarding with parameters suggested in pinpoint documentation.
which got resolved after addition of below parameter : 

-Xbootclasspath/p:/home/arbor/EAP-7.3.0/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.5.1.Final-redhat-00001.jar

Exception : 
java.lang.NoClassDefFoundError: org/wildfly/common/net/HostName
	at org.jboss.logmanager.ExtLogRecord.<init>(ExtLogRecord.java:87)
	at org.jboss.logmanager.Logger.log(Logger.java:796)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	at org.jboss.logging.Logger.logf(Logger.java:2398)
	at org.jboss.msc.service.ServiceLogger_$logger.greeting(ServiceLogger_$logger.java:40)
	at org.jboss.msc.service.ServiceContainerImpl.<clinit>(ServiceContainerImpl.java:90)
	at org.jboss.msc.service.ServiceContainer$Factory.create(ServiceContainer.java:250)
	at org.jboss.as.server.BootstrapImpl$ShutdownHook.register(BootstrapImpl.java:232)
	at org.jboss.as.server.BootstrapImpl$ShutdownHook.access$100(BootstrapImpl.java:222)
	at org.jboss.as.server.BootstrapImpl.<init>(BootstrapImpl.java:73)
	at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:278)
	at org.jboss.as.server.Main.main(Main.java:106)
	at org.jboss.modules.Module.run(Module.java:352)
	at org.jboss.modules.Module.run(Module.java:320)
	at org.jboss.modules.Main.main(Main.java:593)

**Comment by vinicanuto** [comment]
I had the same problem, and it was solved by adding the wildfly-common-XX.jar at the classpath as mentioned.

> we observed below exception while Pinpoint onboarding with parameters suggested in pinpoint documentation. which got resolved after addition of below parameter :
> 
> -Xbootclasspath/p:/home/arbor/EAP-7.3.0/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.5.1.Final-redhat-00001.jar
> 
> Exception : java.lang.NoClassDefFoundError: org/wildfly/common/net/HostName at org.jboss.logmanager.ExtLogRecord.(ExtLogRecord.java:87) at org.jboss.logmanager.Logger.log(Logger.java:796) at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53) at org.jboss.logging.Logger.logf(Logger.java:2398) at org.jboss.msc.service.ServiceLogger_$logger.greeting(ServiceLogger_$logger.java:40) at org.jboss.msc.service.ServiceContainerImpl.(ServiceContainerImpl.java:90) at org.jboss.msc.service.ServiceContainer$Factory.create(ServiceContainer.java:250) at org.jboss.as.server.BootstrapImpl$ShutdownHook.register(BootstrapImpl.java:232) at org.jboss.as.server.BootstrapImpl$ShutdownHook.access$100(BootstrapImpl.java:222) at org.jboss.as.server.BootstrapImpl.(BootstrapImpl.java:73) at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:278) at org.jboss.as.server.Main.main(Main.java:106) at org.jboss.modules.Module.run(Module.java:352) at org.jboss.modules.Module.run(Module.java:320) at org.jboss.modules.Main.main(Main.java:593)
