### ISSUE TITLE
There are no running agents once installation is done.

### ISSUE THREAD

**Issue by raghuram7171** [pinpoint-apm/pinpoint#8252]
### Discussed in https://github.com/pinpoint-apm/pinpoint/discussions/8251

<div type='discussions-op-text'>

<sup>Originally posted by **raghuram7171** September 23, 2021</sup>
Hi Team,

I have installed pinpoint with the latest release 2.3.0
Post installation i am getting the empty page in pinpoint web saying "There are no running agents."
my java version on both web node and agent node is
java version "11.0.11" 2021-04-20 LTS

![image](https://user-images.githubusercontent.com/91255926/134488469-7ea82d9a-4c46-47c8-99f4-66c20467a07b.png)

I followed the below steps while installation.
could you please help me resolving the issue.

Commands used:
```
[apt@phoenix67889]~/pinpoint% cat collector.sh
java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.3.0.jar
[apt@phoenix67889]~/pinpoint% cat web.sh
java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-web-boot-2.3.0.jar
[apt@phoenix67889]~/pinpoint%
```

From agent side:
I added the properties under catalina.sh
```
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/scratch/occuser/pinpoint/pinpoint-agent-2.3.0/pinpoint-bootstrap-2.3.0.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=pp09222021"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=commerce"
```
Running below command
` java -javaagent:/scratch/occuser/pinpoint/pinpoint-agent-2.3.0/pinpoint-bootstrap-2.3.0.jar -Dpinpoint.agentId=pp09222021 -Dpinpoint.applicationName=commerce`

I modified the ip address properties under these files and provided the collector ip details.
```
pinpoint-root.config:20:profiler.transport.grpc.collector.ip=100.108.142.188
pinpoint-root.config:111:profiler.collector.ip=100.108.142.188
profiles/release/pinpoint.config:20:profiler.transport.grpc.collector.ip=100.108.142.188
profiles/release/pinpoint.config:26:profiler.collector.ip=100.108.142.188
profiles/local/pinpoint.config:20:profiler.transport.grpc.collector.ip=100.108.142.188
profiles/local/pinpoint.config:26:profiler.collector.ip=100.108.142.188
```

But i am not getting metrics in web.
am i missing something please help me in this.
attached the pinpoint agent log and command log while starting up the agent.
kindly please help me here.

[pinpoint.log](https://github.com/pinpoint-apm/pinpoint/files/7216692/pinpoint.log)
[command.log](https://github.com/pinpoint-apm/pinpoint/files/7216700/command.log)

</div>

**Comment by emeroad** [comment]
```
09-23 10:06:52.052 [           main] DEBUG i.n.u.i.NativeLibraryLoader              -- Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path: [/qa/jenkins/node-software/ora-cloud-client/12.1/client64/lib, ., /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:827) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1871) ~[?:?]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341) [netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) [netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at com.navercorp.pinpoint.grpc.client.ChannelTypeFactory.newEpollChannelType(ChannelTypeFactory.java:32) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.ChannelTypeFactory.newChannelType(ChannelTypeFactory.java:27) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.DefaultChannelFactory.getChannelType(DefaultChannelFactory.java:105) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.DefaultChannelFactory.<init>(DefaultChannelFactory.java:89) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.DefaultChannelFactoryBuilder.build(DefaultChannelFactoryBuilder.java:89) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.profiler.context.provider.grpc.SpanGrpcDataSenderProvider.get(SpanGrpcDataSenderProvider.java:95) [pinpoint-profiler-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.profiler.context.provider.grpc.SpanGrpcDataSenderProvider.get(SpanGrpcDataSenderProvider.java:53) [pinpoint-profiler-2.3.0.jar:2.3.0]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85) [guice-4.2.2.jar:?]
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59) [guice-4.2.2.jar:?]
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.2.2.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) [guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:57) [guice-4.2.2.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42) [guice-4.2.2.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) [guice-4.2.2.jar:?]
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60) [guice-4.2.2.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.2.2.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) [guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) [guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211) [guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182) [guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109) [guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) [guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:78) [guice-4.2.2.jar:?]
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:93) [pinpoint-profiler-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:111) [pinpoint-profiler-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:87) [pinpoint-profiler-2.3.0.jar:2.3.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) [?:?]
	at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:52) [?:2.3.0]
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41) [?:2.3.0]
	at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:47) [?:2.3.0]
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:139) [?:2.3.0]
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:89) [?:2.3.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513) [?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525) [?:?]
09-23 10:06:52.052 [           main] DEBUG i.n.u.i.NativeLibraryLoader              -- netty_transport_native_epoll_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path: [/qa/jenkins/node-software/ora-cloud-client/12.1/client64/lib, ., /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:827) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1871) ~[?:?]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) [netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at com.navercorp.pinpoint.grpc.client.ChannelTypeFactory.newEpollChannelType(ChannelTypeFactory.java:32) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.ChannelTypeFactory.newChannelType(ChannelTypeFactory.java:27) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.DefaultChannelFactory.getChannelType(DefaultChannelFactory.java:105) [pinpoint-grpc-2.3.0.jar:2.3.0]
	at com.navercorp.pinpoint.grpc.client.DefaultChannelFactory.<init>(DefaultChannelFactory.java:89) [pinpoint-grpc-2.3.0.jar:2.3.0]
```
Failed to load netty's epoll native library.


Does netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar exist in $PINPOINT_HOME/lib?


### Workaound 
Change `profiler.transport.grpc.*.channel-type` to EPOLL in $PINPOINT_HOME/pinpoint-root.config
```
##  AUTO, NIO, EPOLL
profiler.transport.grpc.agent.sender.channel-type=NIO
profiler.transport.grpc.metadata.sender.channel-type=NIO
profiler.transport.grpc.stat.sender.channel-type=NIO
profiler.transport.grpc.span.sender.channel-type=NIO
```
