### ISSUE TITLE
GrpcCommandService - UNIMPLEMENTED: HTTP status code 404

### ISSUE THREAD

**Issue by philippe-granet** [pinpoint-apm/pinpoint#8285]
- [X] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
2.3.0 etc.

#### Describe the bug
I observe these error logs when my application call an url that respond with HTTP 404:
```
09-30 23:49:07.007 [-Executor(12-0)] WARN  c.n.p.p.r.g.GrpcCommandService           -- Failed to command stream, cause=UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,x-content-type-options=nosniff,content-length=19,date=Thu, 30 Sep 2021 21:49:07 GMT)
DATA-----------------------------
404 page not found

io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,x-content-type-options=nosniff,content-length=19,date=Thu, 30 Sep 2021 21:49:07 GMT)
DATA-----------------------------
404 page not found

        at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.36.2.jar:1.36.2]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.36.2.jar:1.36.2]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.36.2.jar:2.3.0]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.36.2.jar:2.3.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.36.2.jar:2.3.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.36.2.jar:2.3.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar:2.3.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar:2.3.0]
```

#### What did you do to trigger the bug?
My application call an url that respond with HTTP 404

#### Expected behavior
No erreor logs with `UNIMPLEMENTED: HTTP status code 404``

**Comment by koo-taejin** [comment]
Hi @philippe-granet 

Please let me know your whole Pinpoint environment.

```
Ex) 
Agent 2.2.0
Collector 2.3.0
Web 2.2.0
 ```

Thanks :)

**Comment by philippe-granet** [comment]
@koo-taejin all in version 2.3.0

**Comment by srouaix** [comment]
Hi @koo-taejin I have the exactly same issue. 

I explain you the context. We installed pinpoint on a cluster swarm. We have a DNS to access to pinpoint. The traffic pass by traefik for the routing on cluster swarm. We have multiple applications with the agent. All application are on windows VM. Agent and server use the same version 2.3.0 . Always work perfectly except we had an issue on the cluster Swarm and we need to stop and restart with a 24 hours of delays between the stop and the restart. After the restart all agent doesn't succes to reconnect to the agent with the same error than @philippe-granet .

If we restart each application with agent, the agent succeed to reconnect to the server. 

Do you have an idea ?

Reagard
