### ISSUE TITLE
there is no data displayed on web page

### ISSUE THREAD

**Issue by AlexDingSZ** [pinpoint-apm/pinpoint#8433]
#### Prerequisites
pinpoint 2.3.1
hbase：1.2.6

log：
11-29 23:36:53.053 [cAgent-Server-1] WARN  c.n.p.c.r.g.s.AgentService               : Failed to ping stream, id=1, cause=CANCELLED: client cancelled
io.grpc.StatusRuntimeException: CANCELLED: client cancelled
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:284) [grpc-stub-1.36.2.jar!/:1.36.2]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:844) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar!/:1.36.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
11-29 23:36:53.053 [pcStat-Server-4] WARN  c.n.p.c.r.g.s.StatService                : Failed to stat stream, cause=CANCELLED: client cancelled
io.grpc.StatusRuntimeException: CANCELLED: client cancelled
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:284) [grpc-stub-1.36.2.jar!/:1.36.2]
	at com.navercorp.pinpoint.grpc.server.flowcontrol.StreamExecutorServerInterceptor$1.onCancel(StreamExecutorServerInterceptor.java:96) [pinpoint-grpc-2.3.1.jar!/:2.3.1]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:844) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar!/:1.36.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
11-29 23:36:53.053 [cAgent-Server-4] WARN  c.n.p.c.r.g.s.c.GrpcCommandService       : Failed to command stream, pet-java-app:paypay-exe:1638195591396 => local, cause=CANCELLED: client cancelled
io.grpc.StatusRuntimeException: CANCELLED: client cancelled
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:284) [grpc-stub-1.36.2.jar!/:1.36.2]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:844) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar!/:1.36.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
11-29 23:36:53.053 [cAgent-Server-1] INFO  c.n.p.c.r.g.s.AgentLifecycleListener     : close:PingSession{id=5, header=Header{name='agent', agentId='paypay-exe', agentName='null', applicationName='pet-java-app', agentStartTime=1638195591396, socketId=46, serviceType=1210, supportCommandCodeList=null, properties={}}, eventIdAllocator=1, serviceType=-1, updated=false, lastPingTimeMillis=1638200171116}/ShutdownEventListener{shutdown=false}
11-29 23:36:53.053 [pcSpan-Server-4] WARN  c.n.p.c.r.g.s.SpanService                : Failed to span stream, Header{name='span', agentId='paypay-exe', agentName='null', applicationName='pet-java-app', agentStartTime=1638195591396, socketId=-1, serviceType=1210, supportCommandCodeList=null, properties={}} cause=CANCELLED: client cancelled
io.grpc.StatusRuntimeException: CANCELLED: client cancelled
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:284) [grpc-stub-1.36.2.jar!/:1.36.2]
	at com.navercorp.pinpoint.grpc.server.flowcontrol.StreamExecutorServerInterceptor$1.onCancel(StreamExecutorServerInterceptor.java:96) [pinpoint-grpc-2.3.1.jar!/:2.3.1]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96) [grpc-api-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:844) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar!/:1.36.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar!/:1.36.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
11-29 23:36:53.053 [cAgent-Server-4] INFO  c.n.p.c.r.g.PinpointGrpcServer           : close() will be started. ( remoteAddress:/192.168.125.135:33698, agentInfo:pet-java-app:paypay-exe:1638195591396, closeState:BEING_CLOSE_BY_CLIENT
11-29 23:36:53.053 [cAgent-Server-4] INFO  c.n.p.c.r.g.PinpointGrpcServer           : pet-java-app:paypay-exe:1638195591396 <=> local all streamChannels will be close.
11-29 23:37:01.001 [pcStat-Server-1] INFO  .p.g.s.f.StreamExecutorServerInterceptor : Initialize schedule listener. statStreamExecutorInterceptor v1.Stat/SendAgentStat, headers=Metadata(content-type=application/grpc,user-agent=grpc-java-netty/1.36.2,agentid=paypay-exe,applicationname=pet-java-app,servicetype=1210,starttime=1638200202482,grpc-accept-encoding=gzip), initNumMessages=100, scheduler=StreamExecutorRejectedExecutionRequestScheduler{scheduledExecutorService=com.navercorp.pinpoint.collector.receiver.grpc.service.StreamExecutorServerInterceptorFactory$1@50e2c835, rejectedExecutionListenerFactory=com.navercorp.pinpoint.grpc.server.flowcontrol.RejectedExecutionListenerFactory@15e05c4d}, listener=Listener{rejectedExecutionListener=RejectedExecutionListener{rejectedExecutionCounter=0, serverCall=DefaultServerCallWrapper{serverCall=io.grpc.internal.ServerCallImpl@243f4ee2, agentId='paypay-exe', applicationName='pet-java-app'}}}
11-29 23:37:01.001 [cAgent-Server-5] INFO  c.n.p.c.r.g.s.c.GrpcCommandService       : AgentInfo{pet-java-app:paypay-exe:1638200202482:} => local. handleCommandV2(). transportId:9, supportCommandCodeList[740, 710, 730, 750]
11-29 23:37:01.001 [pcSpan-Server-1] INFO  .p.g.s.f.StreamExecutorServerInterceptor : Initialize schedule listener. spanStreamExecutorInterceptor v1.Span/SendSpan, headers=Metadata(content-type=application/grpc,user-agent=grpc-java-netty/1.36.2,agentid=paypay-exe,applicationname=pet-java-app,servicetype=1210,starttime=1638200202482,grpc-accept-encoding=gzip), initNumMessages=100, scheduler=StreamExecutorRejectedExecutionRequestScheduler{scheduledExecutorService=com.navercorp.pinpoint.collector.receiver.grpc.service.StreamExecutorServerInterceptorFactory$1@70d0ed73, rejectedExecutionListenerFactory=com.navercorp.pinpoint.grpc.server.flowcontrol.RejectedExecutionListenerFactory@74ef67b1}, listener=Listener{rejectedExecutionListener=RejectedExecutionListener{rejectedExecutionCounter=0, serverCall=DefaultServerCallWrapper{serverCall=io.grpc.internal.ServerCallImpl@96544d, agentId='paypay-exe', applicationName='pet-java-app'}}}
11-29 23:37:01.001 [cAgent-Server-5] INFO  c.n.p.c.r.g.s.c.GrpcCommandService       : pet-java-app:paypay-exe:1638200202482 => local. ready() transportId:9
11-29 23:37:01.001 [cAgent-Server-5] INFO  c.n.p.c.r.g.s.c.GrpcCommandService       : pet-java-app:paypay-exe:1638200202482 => local. execute supportCommandServiceCodeList:[740, 710, 730, 750]
11-29 23:37:01.001 [cAgent-Server-5] INFO  c.n.p.c.r.g.PinpointGrpcServer           : AgentInfo{pet-java-app:paypay-exe:1638200202482:} handleHandshake() started. data:[740, 710, 730, 750]
11-29 23:37:01.001 [cAgent-Server-3] INFO  c.n.p.c.r.g.s.AgentLifecycleListener     : connect:PingSession{id=9, header=Header{name='agent', agentId='paypay-exe', agentName='null', applicationName='pet-java-app', agentStartTime=1638200202482, socketId=1, serviceType=1210, supportCommandCodeList=null, properties={}}, eventIdAllocator=0, serviceType=-1, updated=false, lastPingTimeMillis=1638200221044}
11-29 23:37:01.001 [Agent-Worker-40] INFO  c.n.p.c.r.g.s.AgentLifecycleListener     : connect:PingSession{id=9, header=Header{name='agent', agentId='paypay-exe', agentName='null', applicationName='pet-java-app', agentStartTime=1638200202482, socketId=1, serviceType=1210, supportCommandCodeList=null, properties={}}, eventIdAllocator=1, serviceType=1210, updated=false, lastPingTimeMillis=1638200221044}
11-29 23:39:52.052 [weeper-pool3-t1] INFO  o.a.h.h.i.AbstractRpcClient              : Cleanup idle connection to prd--0006.novalocal:19434
11-29 23:40:49.049 [gent-Worker-114] INFO  c.n.p.c.r.g.s.AgentLifecycleListener     : connect:PingSession{id=3, header=Header{name='agent', agentId='pp1', agentName='null', applicationName='ppp', agentStartTime=1638200144515, socketId=5, serviceType=1210, supportCommandCodeList=null, properties={}}, eventIdAllocator=1, serviceType=1210, updated=false, lastPingTimeMillis=1638200338912}
^C

**Comment by AlexDingSZ** [comment]
![image](https://user-images.githubusercontent.com/24445777/143901430-346aed8d-a9cc-4415-8101-2aeb155cce94.png)
