### ISSUE TITLE
 dispatch failed

### ISSUE THREAD

**Issue by daekyocnslab** [pinpoint-apm/pinpoint#8462]
#### What version of pinpoint are you using?
v2.2.2 

#### Describe your problem**
동일한 조건의 pinpoint apm 서버 2대를 운영중입니다.
어느날부터 한쪽 서버에서 data 수집이 되지 않고
아래와 같은 오류 메시지가 보였습니다.
Two pinpoint apm servers under the same conditions are in operation.
Since one day, data has not been collected from one server.
I got the error message below
 

#### Logs
 12-03 17:30:10.010 [r-Executor(5-0)] WARN  c.n.p.p.s.g.s.DefaultStreamTask          -- dispatch failed
java.lang.NullPointerException: null
        at  com.navercorp.pinpoint.grpc.trace.PAcceptEvent$ Builder.setRpc( PAcceptEvent.java:665) ~[ pinpoint-grpc-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.newAcceptEvent( GrpcSpanMessageConverter.java:174) ~[ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.buildPSpan( GrpcSpanMessageConverter.java:114) ~[ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.toMessage( GrpcSpanMessageConverter.java:89) ~[ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.toMessage( GrpcSpanMessageConverter.java:59) ~[ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender$ 1.onDispatch( SpanGrpcDataSender.java:58) ~[ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.sender.grpc.stream.DefaultStreamTask$ 2.dispatch( DefaultStreamTask.java:92) [ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  com.navercorp.pinpoint.profiler.sender.grpc.stream.DefaultStreamTask$ 2.run( DefaultStreamTask.java:78) [ pinpoint-profiler-2.2.2.jar:2.2.2]
        at  java.util.concurrent.Executors$ RunnableAdapter.call( Executors.java:511) [?:1.8.0_265]
        at  java.util.concurrent.FutureTask.run( FutureTask.java:266) [?:1.8.0_265]
        at  java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at  java.util.concurrent.ThreadPoolExecutor$ Worker.run( ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at  java.lang.Thread.run( Thread.java:748) [?:1.8.0_265]

**Comment by emeroad** [comment]
It seems that Rpc field is not recorded in the server plugin(tomcat, spring-boot...)
Can you find the problem plugin?

**Comment by bungabear** [comment]
In Spring Boot, has same issue with pinpoint v2.3.3

I also can not find no more detail log.

```
01-19 03:02:58.058 [r-Executor(5-0)] WARN  c.n.p.p.s.g.s.DefaultStreamTask          -- dispatch failed
java.lang.NullPointerException: null
        at com.navercorp.pinpoint.grpc.trace.PAcceptEvent$Builder.setRpc(PAcceptEvent.java:665) ~[pinpoint-grpc-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.newAcceptEvent(GrpcSpanMessageConverter.java:175) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.buildPSpan(GrpcSpanMessageConverter.java:115) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.toMessage(GrpcSpanMessageConverter.java:90) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.context.grpc.GrpcSpanMessageConverter.toMessage(GrpcSpanMessageConverter.java:60) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender$1.onDispatch(SpanGrpcDataSender.java:59) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender$1.onDispatch(SpanGrpcDataSender.java:56) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.sender.grpc.stream.DefaultStreamTask$2.dispatch(DefaultStreamTask.java:92) [pinpoint-profiler-2.3.3.jar:2.3.3]
        at com.navercorp.pinpoint.profiler.sender.grpc.stream.DefaultStreamTask$2.run(DefaultStreamTask.java:78) [pinpoint-profiler-2.3.3.jar:2.3.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
```

**Comment by emeroad** [comment]
If it is possible to reproduce the problem, please tell me how to reproduce it.

We are also using spring-boot, but no problems.
