### ISSUE TITLE
404 error in agent log after restarting server stack

### ISSUE THREAD

**Issue by srouaix** [pinpoint-apm/pinpoint#8568]
- [X] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
V2.3.0

#### Describe your problem
We installed pinpoint on a cluster swarm. We have a DNS to access to pinpoint. The traffic pass by traefik for the routing on cluster swarm. We have multiple applications with the agent. All application are on Windows VM. Agent and server use the same version 2.3.0 . Always work perfectly except we had an issue on the cluster Swarm and we need to stop and restart with a 24 hours of delays between the stop and the restart. After the restart all agent doesn't succes to reconnect to the agent with the same error (see log)

If we restart each application with agent, the agent succeed to reconnect to the server. 

Do you have an idea ?

This is debug log
```12-15 16:07:49.049 [el-Worker(11-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0xd4885756, L:/192.168.171.112:60020 - R:pinpoint.svc.****.fr/172.20.99.186:9991] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=5
12-15 16:07:49.049 [el-Worker(11-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0xd4885756, L:/192.168.171.112:60020 - R:pinpoint.svc.****.fr/172.20.99.186:9991] INBOUND RST_STREAM: streamId=58385 errorCode=5
12-15 16:07:49.049 [ect-thread(4-0)] INFO  c.n.p.p.s.g.StatGrpcDataSender           -- newStream StatStream
12-15 16:07:49.049 [ect-thread(4-0)] INFO  c.n.p.p.s.g.ResponseStreamObserver       -- beforeStart DefaultStreamEventListener{StatStream-43785}
12-15 16:07:49.049 [el-Worker(14-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0x77b0af97, L:/192.168.171.112:60018 - R:pinpoint.svc.****.fr/172.20.99.186:9992] OUTBOUND HEADERS: streamId=29201 headers=GrpcHttp2OutboundHeaders[:authority: pinpoint.svc.****.fr:9992, :path: /v1.Stat/SendAgentStat, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.36.2, agentid: Business_Contrat, applicationname: Business_Contrat, servicetype: 1000, starttime: 1639451149544, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
12-15 16:07:49.049 [-Executor(15-0)] INFO  c.n.p.p.s.g.ResponseStreamObserver       -- onReadyHandler DefaultStreamEventListener{StatStream-43785} isReadyCount:1
12-15 16:07:49.049 [-Executor(15-0)] INFO  c.n.p.p.s.g.s.StreamExecutor             -- stream execute name='StatStream-43785
12-15 16:07:49.049 [el-Worker(14-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0x77b0af97, L:/192.168.171.112:60018 - R:pinpoint.svc.****.fr/172.20.99.186:9992] INBOUND HEADERS: streamId=29201 headers=GrpcHttp2ResponseHeaders[:status: 404, content-type: text/plain; charset=utf-8, x-content-type-options: nosniff, content-length: 19, date: Wed, 15 Dec 2021 15:07:49 GMT] padding=0 endStream=false
12-15 16:07:49.049 [-Executor(16-0)] INFO  c.n.p.p.s.g.s.DefaultStreamTask          -- dispatch start name='StatStream-43785
12-15 16:07:49.049 [el-Worker(14-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0x77b0af97, L:/192.168.171.112:60018 - R:pinpoint.svc.****.fr/172.20.99.186:9992] INBOUND DATA: streamId=29201 padding=0 endStream=true length=19 bytes=3430342070616765206e6f7420666f756e640a
12-15 16:07:49.049 [el-Worker(14-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0x77b0af97, L:/192.168.171.112:60018 - R:pinpoint.svc.****.fr/172.20.99.186:9992] INBOUND RST_STREAM: streamId=29201 errorCode=0
12-15 16:07:49.049 [el-Worker(14-0)] DEBUG i.g.n.NettyClientHandler                 -- [id: 0x77b0af97, L:/192.168.171.112:60018 - R:pinpoint.svc.****.fr/172.20.99.186:9992] OUTBOUND RST_STREAM: streamId=29201 errorCode=8
12-15 16:07:49.049 [-Executor(15-0)] INFO  c.n.p.p.s.g.ResponseStreamObserver       -- Failed to stream, name=DefaultStreamEventListener{StatStream-43785}, cause=UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,x-content-type-options=nosniff,content-length=19,date=Wed, 15 Dec 2021 15:07:49 GMT)
DATA-----------------------------
404 page not found

io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,x-content-type-options=nosniff,content-length=19,date=Wed, 15 Dec 2021 15:07:49 GMT)
DATA-----------------------------
404 page not found

	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.36.2.jar:1.36.2]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.36.2.jar:1.36.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.36.2.jar:2.3.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.36.2.jar:2.3.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.36.2.jar:2.3.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.36.2.jar:2.3.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar:2.3.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar:2.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) `[?:1.8.0_172]
```

**Comment by liucx1201** [comment]
中文：因为你没有做hbase数据的持久化导致，重启后数据丢失无法重连

**Comment by srouaix** [comment]
no it is not this because the persistance in hbase activated.
