### ISSUE TITLE
java.util.concurrent.CompletionException

### ISSUE THREAD

**Issue by yuyivic** [pinpoint-apm/pinpoint#8676]
Upgrade the collector from v1.8.0 to v2.3.3, open the web console and report an error：

java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: slot not found slotTime=32766, count=1, schema={typeCode=2, fastSlot=HistogramSlot{slotTime=1000, slotType=FAST, slotName='1s'}, normalSlot=HistogramSlot{slotTime=3000, slotType=NORMAL, slotName='3s'}, slowSlot=HistogramSlot{slotTime=5000, slotType=SLOW, slotName='5s'}, verySlowSlot=HistogramSlot{slotTime=0, slotType=VERY_SLOW, slotName='Slow'}, errorSlot=HistogramSlot{slotTime=-1, slotType=ERROR, slotName='Error'}, fastErrorSlot=HistogramSlot{slotTime=-1000, slotType=FAST_ERROR, slotName='1s'}, normalErrorSlot=HistogramSlot{slotTime=-3000, slotType=NORMAL_ERROR, slotName='3s'}, slowErrorSlot=HistogramSlot{slotTime=-5000, slotType=SLOW_ERROR, slotName='5s'}, verySlowErrorSlot=HistogramSlot{slotTime=-9999, slotType=VERY_SLOW_ERROR, slotName='Slow'}}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at com.navercorp.pinpoint.web.task.RequestContextPropagatingTaskDecorator$RequestContextPropagatingRunnable.run(RequestContextPropagatingTaskDecorator.java:50)
	at com.navercorp.pinpoint.web.task.SecurityContextPropagatingTaskDecorator$SecurityContextPropagatingRunnable.run(SecurityContextPropagatingTaskDecorator.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/22007456/155151432-5418cd0f-6527-4dde-94bd-22448bf14854.png">

**Comment by minwoo-jung** [comment]
Hello @yuyivic 
Have you upgraded pinpoint-web ?
Since schema and properties have been changed, both web and collector must be upgraded together.

**Comment by emeroad** [comment]
You must use the same version of collector and web.
