### ISSUE TITLE
initializing deadlock issue

### ISSUE THREAD

**Issue by jiho-song-yanolja** [pinpoint-apm/pinpoint#8712]
#### What version of pinpoint are you using?
v2.3.3

#### Describe the bug
I found a deadlock while initializing pintpoint version 2.3.3.

Because of this deadlock, the application system couldn't be initialized at all.

Personally I suspect two of same java constructor initializing locks may be locked each other, but not sure if this is the case, since we don't have any more details with the stack trace.

I attached the thread dump along with this.

`03-17 08:13:12.012 [eadlock-monitor] WARN c.n.p.p.m.DeadlockMonitorTask -- ================================================================ [PINPOINT] Found one Java-level deadlock: If pinpoints affect the deadlock below, please put all the information posted on pinpoint's github. (https://github.com/naver/pinpoint/issues) ================================================================ "main" Id=1 BLOCKED on jdk.internal.loader.URLClassPath@4b98bcf0 owned by "Attach Listener" Id=33 at java.base@11.0.14.1/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:423) - blocked on jdk.internal.loader.URLClassPath@4b98bcf0 at java.base@11.0.14.1/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:314) at java.base@11.0.14.1/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:695) at java.base@11.0.14.1/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) at java.base@11.0.14.1/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) at java.base@11.0.14.1/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base@11.0.14.1/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at app//org.springframework.boot.loader.jar.JarFile.getUrl(JarFile.java:321) at app//org.springframework.boot.loader.archive.JarFileArchive.getUrl(JarFileArchive.java:73) at app//org.springframework.boot.loader.Launcher.createClassLoader(Launcher.java:62) at app//org.springframework.boot.loader.Launcher.launch(Launcher.java:49) at app//org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) "Attach Listener" Id=33 BLOCKED on [I@a131288 owned by "main" Id=1 at java.base@11.0.14.1/java.lang.Class.getDeclaredConstructors0(Native Method) - blocked on [I@a131288 at java.base@11.0.14.1/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137) at java.base@11.0.14.1/java.lang.Class.getConstructor0(Class.java:3342) at java.base@11.0.14.1/java.lang.Class.newInstance(Class.java:556) at java.base@11.0.14.1/java.net.URL.lookupViaProperty(URL.java:1291) at java.base@11.0.14.1/java.net.URL.getURLStreamHandler(URL.java:1441) at java.base@11.0.14.1/java.net.URL.<init>(URL.java:451) at java.base@11.0.14.1/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:720) at java.base@11.0.14.1/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:494) at java.base@11.0.14.1/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:477) at java.base@11.0.14.1/java.security.AccessController.doPrivileged(Native Method) at java.base@11.0.14.1/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:476) at java.base@11.0.14.1/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:445) at java.base@11.0.14.1/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:314) at java.base@11.0.14.1/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:695) at java.base@11.0.14.1/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) at java.base@11.0.14.1/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) at java.base@11.0.14.1/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base@11.0.14.1/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.instrument@11.0.14.1/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431) at java.instrument@11.0.14.1/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)`

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Our pinpoint agent is up and running by ebexentenstion of AWS while initializing the instance.
2. Among those pinpoint configuration(pinpoint.config), we set profiler.kafka.producer.enable to true, profiler.redis.lettuce.enable to false, profiler/tomcat/excludeurl to /health. (I'm not sure if this is relevant to the issue)

#### Expected behavior
pinpoint agent should be initialized without any problem.

#### Additional context
I feel sorry If the log wasn't helpful enough.
I would appreciate if you can guide us on finding better information/logs for debugging.
Thank you.

**Comment by emeroad** [comment]
If the problem is reproduced, could you please create a thread dump?

```
jstack -l ${JAVA_PID} > thread-dump.txt
```
https://www.baeldung.com/java-thread-dump

**Comment by testn** [comment]
Did you manage to reproduce it?

**Comment by lu1235353884** [comment]
we use pinpoint version is  v2.3.0
we found a deadlock while initializing pintpoint :

Among those pinpoint configuration(pinpoint.config), we set profiler.plugin.disable=com.navercorp.pinpoint.plugin.gson.GsonPlugin

**initializing log：**
1-22 13:31:36.036 [eadlock-monitor] WARN  c.n.p.p.m.DeadlockMonitorTask            -- 
================================================================
[PINPOINT] Found one Java-level deadlock:

If pinpoints affect the deadlock below, please put all the information posted on pinpoint's github.
(https://github.com/naver/pinpoint/issues)
================================================================
"http-nio-32622-exec-61" Id=176 BLOCKED on [I@29708459 owned by "http-nio-32622-exec-55" Id=170
