### ISSUE TITLE
HBase startup Failed in Docker

### ISSUE THREAD

**Issue by Deep407** [pinpoint-apm/pinpoint#8840]
HBase Startup is failing in docker desktop with following error. 

starting master, logging to /opt/hbase/hbase-1.2.6/logs/hbase--master-c349b8e2ae81.out

OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0

starting regionserver, logging to /opt/hbase/hbase-1.2.6/logs/hbase--1-regionserver-c349b8e2ae81.out

create tables

2022-05-05 06:24:01,863 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

2022-05-05 06:24:25,759 ERROR [main] zookeeper.RecoverableZooKeeper: ZooKeeper exists failed after 4 attempts

2022-05-05 06:24:25,760 WARN  [main] zookeeper.ZKUtil: hconnection-0x3eda0aeb0x0, quorum=zoo1:2181,zoo2:2181,zoo3:2181, baseZNode=/hbase Unable to set watcher on znode (/hbase/hbaseid)

org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout

at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:144)

at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)

at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:419)

at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)

at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)

at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:905)

at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:648)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)

at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)

at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:450)

at org.jruby.javasupport.JavaMethod.invokeStaticDirect(JavaMethod.java:362)

at org.jruby.java.invokers.StaticMethodInvoker.call(StaticMethodInvoker.java:58)

at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)

at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)

at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)

at org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)

at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)

at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)

at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)

at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)

at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:191)

at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)

at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)

at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:148)

at org.jruby.RubyClass.newInstance(RubyClass.java:822)

at org.jruby.RubyClass$i$newInstance.call(RubyClass$i$newInstance.gen:65535)

at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:249)

at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)

at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)

at opt.hbase.hbase_minus_1_dot_2_dot_6.bin.hirb.__file__(/opt/hbase/hbase-1.2.6/bin/hirb.rb:131)

at opt.hbase.hbase_minus_1_dot_2_dot_6.bin.hirb.load(/opt/hbase/hbase-1.2.6/bin/hirb.rb)

at org.jruby.Ruby.runScript(Ruby.java:697)

at org.jruby.Ruby.runScript(Ruby.java:690)

at org.jruby.Ruby.runNormally(Ruby.java:597)

at org.jruby.Ruby.runFromMain(Ruby.java:446)

at org.jruby.Main.doRunFromMain(Main.java:369)

at org.jruby.Main.internalRun(Main.java:258)

at org.jruby.Main.run(Main.java:224)

at org.jruby.Main.run(Main.java:208)

at org.jruby.Main.main(Main.java:188)

2022-05-05 06:24:25,764 ERROR [main] zookeeper.ZooKeeperWatcher: hconnection-0x3eda0aeb0x0, quorum=zoo1:2181,zoo2:2181,zoo3:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception

org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout

at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:144)

at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)

at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:419)

at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)

at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)

at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:905)

at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:648)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)

at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)

at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:450)

at org.jruby.javasupport.JavaMethod.invokeStaticDirect(JavaMethod.java:362)

at org.jruby.java.invokers.StaticMethodInvoker.call(StaticMethodInvoker.java:58)

at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)

at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)

at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)

at org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)

at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)

at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)

at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)

at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)

at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:191)

at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)

at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)

at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:148)

at org.jruby.RubyClass.newInstance(RubyClass.java:822)

at org.jruby.RubyClass$i$newInstance.call(RubyClass$i$newInstance.gen:65535)

at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:249)

at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)

at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)

at opt.hbase.hbase_minus_1_dot_2_dot_6.bin.hirb.__file__(/opt/hbase/hbase-1.2.6/bin/hirb.rb:131)

at opt.hbase.hbase_minus_1_dot_2_dot_6.bin.hirb.load(/opt/hbase/hbase-1.2.6/bin/hirb.rb)

at org.jruby.Ruby.runScript(Ruby.java:697)

at org.jruby.Ruby.runScript(Ruby.java:690)

at org.jruby.Ruby.runNormally(Ruby.java:597)

at org.jruby.Ruby.runFromMain(Ruby.java:446)

at org.jruby.Main.doRunFromMain(Main.java:369)

at org.jruby.Main.internalRun(Main.java:258)

at org.jruby.Main.run(Main.java:224)

at org.jruby.Main.run(Main.java:208)

at org.jruby.Main.main(Main.java:188)

**Comment by abitming** [comment]
I had the same problem,Did you solve it？

**Comment by ga-ram** [comment]
Which version were you using? 
I would say check the statuses and logs of zookeeper containers running on your environment.
Docker-specific issues are welcome in https://github.com/pinpoint-apm/pinpoint-docker/issues as well.
