### ISSUE TITLE
Support kafka-clients 3.1.x

### ISSUE THREAD

**Issue by cj848** [pinpoint-apm/pinpoint#8878]
#### What version of pinpoint are you using?
I'm using 2.3.3, but it seems to be the same for a later version.

#### Describe the bug
[polling interceptor code](https://github.com/pinpoint-apm/pinpoint/blob/77ca7601cf46725982db5404204c4dc908fe422b/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/NetworkClientPollInterceptor.java#L85)

[changed kafka-clients code](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/requests/FetchResponse.java#L99)

As in the code above, the compatibility between the current pinpoint code and the latest version of the kafka-clients library is not compatible.
#### What did you do to trigger the bug?
It occurred in the process of upgrading Spring Boot from 2.6.7 -> 2.7.0 instead of directly upgrading kafka-clients, and spring boot users who do not care about the version of kafka-clients will experience an error when linking with pinpoint.

#### Expected behavior
The responseData method of Pinpoint's NetworkClientPollInterceptor must be called normally in kafka-clients versions 3.1.x or higher and 3.0.x versions.

#### Screenshots
![image](https://user-images.githubusercontent.com/5905201/169720125-9b267328-ec9b-426e-9a91-4955828191d9.png)

#### Logs
```java
java.lang.NoSuchMethodError: 'java.util.LinkedHashMap org.apache.kafka.common.requests.FetchResponse.responseData()'
	at com.navercorp.pinpoint.plugin.kafka.interceptor.NetworkClientPollInterceptor.after(NetworkClientPollInterceptor.java:86)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:577)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1297)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollConsumer(KafkaMessageListenerContainer.java:1522)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1512)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1340)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by donguseo** [comment]
@cj848 Did you fix the problem?

**Comment by cj848** [comment]
no i just wrote issue
