### ISSUE TITLE
use openj9 jdk 11, the grpc doesnot work .  java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files

### ISSUE THREAD

**Issue by chenglin321** [pinpoint-apm/pinpoint#8890]
#### Prerequisites
when i use openj9 jdk 11,  start springboot project, the grpc doesnot work. but i changed hotsport jdk11 is fine.

error log： java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files

"material" is springboot project.
run script :
java  -javaagent:/home/pinpoint-agent/pinpoint-bootstrap.jar  -Dpinpoint.agentId=material-test -Dpinpoint.applicationName=material   -jar material.jar

env:
  jdk:
        openjdk version "11.0.14.1" 2022-02-08
        IBM Semeru Runtime Open Edition 11.0.14.1 (build 11.0.14.1+1)
        Eclipse OpenJ9 VM 11.0.14.1 (build openj9-0.30.1, JRE 11 Linux amd64-64-Bit Compressed References 20220210_379 (JIT enabled, AOT enabled)
        OpenJ9   - 9dccbe076
        OMR      - 56c3376ba
        JCL      - 5c423dacd0 based on jdk-11.0.14.1+1)

  pinpoint version: 2.3.1

#### What version of pinpoint are you using?
pinpoint version: 2.3.1

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.xml
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.desktop
[com.navercorp.pinpoint.bootstrap.java9.module.ModuleSupport] loadModule:java.logging
05-27 10:19:28.887 INFO  PinpointStarter                     : pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
05-27 10:19:28.908 INFO  Log4j2LoggingSystem                 : logPath:file:/home/cnhis-pinpoint-agent/profiles/release/log4j2.xml
2022-05-27 10:19:30,389 main ERROR DefaultRolloverStrategy has no parameter that matches element IfFileName
2022-05-27 10:19:30,403 main ERROR DefaultRolloverStrategy has no parameter that matches element IfLastModified
5月 27, 2022 10:19:35 上午 io.grpc.NameResolverRegistry getDefaultRegistry
警告: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using ProGuard, check your configuration
5月 27, 2022 10:19:36 上午 io.grpc.internal.ManagedChannelImpl$2 uncaughtException
严重: [Channel<1>: (192.168.1.225:9993)] Uncaught exception in the SynchronizationContext. Panic!5d453a094ade48cfb2b673a3d816bf38
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:92)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:63)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:405)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:971)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:968)
at pinpoint.agent/pinpoint.agent/io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.client.UnaryCallDeadlineInterceptor.interceptCall(UnaryCallDeadlineInterceptor.java:52)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:910)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ForwardingManagedChannel.newCall (ForwardingManagedChannel.java:63)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.trace.SpanGrpc$SpanStub.sendSpan(SpanGrpc.java:134)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender$3.newStream(SpanGrpcDataSender.java:107)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.ClientStreamingService.newStream(ClientStreamingService.java:20)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.stream.DefaultStreamTask.start(DefaultStreamTask.java:65)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender.startStream(SpanGrpcDataSender.java:119)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender.access$000(SpanGrpcDataSender.java:42)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender$2.run(SpanGrpcDataSender.java:91)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.SpanGrpcDataSender.<init>(SpanGrpcDataSender.java:112)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.SpanGrpcDataSenderProvider.get(SpanGrpcDataSenderProvider.java:103)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.SpanGrpcDataSenderProvider.get(SpanGrpcDataSenderProvider.java:53)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:57)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
at pinpoint.agent/pinpoint.agent/com.google.inject.Guice.createInjector(Guice.java:87)
at pinpoint.agent/pinpoint.agent/com.google.inject.Guice.createInjector(Guice.java:78)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:93)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:111)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:87)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:52)
at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:47)
at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:139)
at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
5月 27, 2022 10:19:36 上午 io.grpc.internal.ManagedChannelImpl$2 uncaughtException
严重: [Channel<3>: (192.168.1.225:9991)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:92)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:63)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:405)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:971)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:968)
at pinpoint.agent/pinpoint.agent/io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.client.UnaryCallDeadlineInterceptor.interceptCall(UnaryCallDeadlineInterceptor.java:50)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:910)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.trace.MetadataGrpc$MetadataStub.requestApiMetaData(MetadataGrpc.java:232)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.MetadataGrpcDataSender.request0(MetadataGrpcDataSender.java:153)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.MetadataGrpcDataSender.access$200(MetadataGrpcDataSender.java:48)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.MetadataGrpcDataSender$2.run(MetadataGrpcDataSender.java:129)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:866)
5月 27, 2022 10:19:36 上午 io.grpc.internal.ManagedChannelImpl$2 uncaughtException
严重: [Channel<5>: (192.168.1.225:9991)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:92)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:63)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:405)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:971)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:968)
at pinpoint.agent/pinpoint.agent/io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.client.UnaryCallDeadlineInterceptor.interceptCall(UnaryCallDeadlineInterceptor.java:52)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:910)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.client.SupportCommandCodeClientInterceptor.interceptCall(SupportCommandCodeClientInterceptor.java:43)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.trace.ProfilerCommandServiceGrpc$ProfilerCommandServiceStub.handleCommandV2(ProfilerCommandServiceGrpc.java:375)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.receiver.grpc.GrpcCommandService.connect(GrpcCommandService.java:78)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.receiver.grpc.GrpcCommandService.<init>(GrpcCommandService.java:66)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.AgentGrpcDataSender.<init>(AgentGrpcDataSender.java:72)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.AgentGrpcDataSenderProvider.newAgentGrpcDataSender(AgentGrpcDataSenderProvider.java:117)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.AgentGrpcDataSenderProvider.get(AgentGrpcDataSenderProvider.java:109)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.AgentGrpcDataSenderProvider.get(AgentGrpcDataSenderProvider.java:55)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:57)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.AgentInfoSenderProvider.get(AgentInfoSenderProvider.java:61)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.AgentInfoSenderProvider.get(AgentInfoSenderProvider.java:37)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
at pinpoint.agent/pinpoint.agent/com.google.inject.Guice.createInjector(Guice.java:87)
at pinpoint.agent/pinpoint.agent/com.google.inject.Guice.createInjector(Guice.java:78)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:93)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:111)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:87)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:52)
at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:47)
at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:139)
at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
5月 27, 2022 10:19:36 上午 io.grpc.internal.ManagedChannelImpl$2 uncaughtException
严重: [Channel<7>: (192.168.1.225:9992)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:92)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:63)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:405)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:971)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at pinpoint.agent/pinpoint.agent/io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:968)
at pinpoint.agent/pinpoint.agent/io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.client.UnaryCallDeadlineInterceptor.interceptCall(UnaryCallDeadlineInterceptor.java:52)
at pinpoint.agent/pinpoint.agent/io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:910)
at pinpoint.agent/pinpoint.agent/io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.grpc.trace.StatGrpc$StatStub.sendAgentStat(StatGrpc.java:134)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.StatGrpcDataSender$3.newStream(StatGrpcDataSender.java:117)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.ClientStreamingService.newStream(ClientStreamingService.java:20)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.stream.DefaultStreamTask.start(DefaultStreamTask.java:65)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.StatGrpcDataSender.startStream(StatGrpcDataSender.java:131)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.StatGrpcDataSender.access$000(StatGrpcDataSender.java:42)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.StatGrpcDataSender$2.run(StatGrpcDataSender.java:105)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.sender.grpc.StatGrpcDataSender.<init>(StatGrpcDataSender.java:122)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.StatGrpcDataSenderProvider.get(StatGrpcDataSenderProvider.java:85)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.grpc.StatGrpcDataSenderProvider.get(StatGrpcDataSenderProvider.java:45)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:57)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
at pinpoint.agent/pinpoint.agent/com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
at pinpoint.agent/pinpoint.agent/com.google.inject.Guice.createInjector(Guice.java:87)
at pinpoint.agent/pinpoint.agent/com.google.inject.Guice.createInjector(Guice.java:78)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:93)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:111)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:87)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:52)
at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:47)
at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:139)
at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
05-27 10:19:36.832 INFO  PinpointStarter                     : pinpoint agent started normally.

**Comment by smilu97** [comment]
Hi! Thanks for reporting bug. We could review overall structures about java module, module-layer, and this bug at OpenJ9 is now resolved at latest.

**Comment by chenxushuo** [comment]
fixed  now?

**Comment by chenglin321** [comment]
> fixed now?

2.5.0 resolved

**Comment by smilu97** [comment]
Adding standalone module occurs duplicated providers in service loader
