### ISSUE TITLE
/getAgentInstallationInfo responds with error

### ISSUE THREAD

**Issue by ga-ram** [pinpoint-apm/pinpoint#8902]
#### What version of pinpoint are you using?
master

#### Describe the bug
https://github.com/pinpoint-apm/pinpoint-docker/issues/138

#### What did you do to trigger the bug?
Pinpoint web > config > installation

#### Expected behavior
Proper response is expected instead of current error message

**Comment by liucx1201** [comment]
I is use docker-compose installation,How should we solve the problem？

**Comment by emeroad** [comment]
AgentDownloadController declaration is missing in AuthorizationConfig.

**Comment by liucx1201** [comment]
06-02 15:32:39.951 INFO  PinpointBootStrap                   : JavaAgentPath:/wls/pinpoint/pinpoint-bootstrap-2.4.0.jar 
06-02 15:32:39.952 INFO  AgentDirBaseClassPathResolver       : Agent original-path:/pinpoint 
06-02 15:32:39.953 INFO  AgentDirBaseClassPathResolver       : Agent real-path:/wls/pinpoint 
06-02 15:32:39.956 WARN  BootDir                             : too many pinpoint-commons.jar found. [/wls/pinpoint/boot/pinpoint-commons-2.4.0.jar, /wls/pinpoint/boot/pinpoint-commons-2.3.3.jar] 
06-02 15:32:39.957 WARN  PinpointBootStrap                   : AgentDir resolve fail Caused by:pinpoint-commons-x.x.x(-SNAPSHOT)(-RCx).jar not found 
java.lang.IllegalStateException: pinpoint-commons-x.x.x(-SNAPSHOT)(-RCx).jar not found 
	at com.navercorp.pinpoint.bootstrap.agentdir.BootDir.verify(BootDir.java:57) 
	at com.navercorp.pinpoint.bootstrap.agentdir.BootDir.<init>(BootDir.java:41) 
	at com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver.resolveBootDir(AgentDirBaseClassPathResolver.java:105) 
	at com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver.resolve(AgentDirBaseClassPathResolver.java:74) 
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.resolveAgentDir(PinpointBootStrap.java:132) 
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.start(PinpointBootStrap.java:100) 
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:59) 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:498) 
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386) 
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401) 
06-02 15:32:39.958 WARN  PinpointBootStrap                   : Agent Directory Verify fail. skipping agent loading. 

agent  start fail  @ga-ram @emeroad

**Comment by liucx1201** [comment]
https://github.com/pinpoint-apm/pinpoint/releases/download/v2.4.0/pinpoint-agent-2.4.0.tar.gz

**Comment by minwoo-jung** [comment]
https://github.com/pinpoint-apm/pinpoint/pull/8920
