### ISSUE TITLE
org.apache.hadoop.hbase.TableNotFoundException: Table 'ApplicationIndex' was not found, got: AgentInfo.

### ISSUE THREAD

**Issue by codecodesam** [pinpoint-apm/pinpoint#9068]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [Y] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

Today, i clone the pinpoint-apm/pinpoint-docker.
I modify the docker-compose.yml (remove mysql,flink).
Then I run the command "docker-compose pull && docker-compose up -d".

I input the url "http://localhost:8080/main" and get a tip "org.apache.hadoop.hbase.TableNotFoundException: Table 'ApplicationIndex' was not found, got: AgentInfo."

I see the log in pinpoint-collector
```
--- first error
com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed 1 action: Table 'ApplicationIndex' was not found, got: AgentInfo.: 1 time, servers with issues: null; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Table 'ApplicationIndex' was not found, got: AgentInfo.: 1 time, servers with issues: null
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:760) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:298) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseApplicationIndexDao.insert(HbaseApplicationIndexDao.java:72) ~[classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseApplicationIndexDao$$FastClassBySpringCGLIB$$9475ae3b.invoke(<generated>) ~[classes!/:2.4.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseApplicationIndexDao$$EnhancerBySpringCGLIB$$6e4b1f05.insert(<generated>) ~[classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.service.AgentInfoService.insert(AgentInfoService.java:45) ~[classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.handler.grpc.GrpcAgentInfoHandler.handleAgentInfo(GrpcAgentInfoHandler.java:88) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.handler.grpc.GrpcAgentInfoHandler.handleRequest(GrpcAgentInfoHandler.java:71) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.AgentDispatchHandler.dispatchRequestMessage(AgentDispatchHandler.java:88) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchRequestMessage(DelegateDispatchHandler.java:70) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.grpc.service.SimpleRequestHandlerAdaptor.request(SimpleRequestHandlerAdaptor.java:54) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.grpc.service.AgentService$1.run(AgentService.java:78) [classes!/:2.4.0]
        at io.grpc.Context$1.run(Context.java:566) [grpc-context-1.43.2.jar!/:1.43.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Table 'ApplicationIndex' was not found, got: AgentInfo.: 1 time, servers with issues: null
        at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.makeException(AsyncProcess.java:295) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.access$2300(AsyncProcess.java:271) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.AsyncProcess.waitForAllPreviousOpsAndReset(AsyncProcess.java:1924) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:303) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:266) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1477) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1024) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$7.doInTable(HbaseTemplate2.java:301) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:751) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        ... 23 more

--- second error

com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed 1 action: Table 'ApplicationIndex' was not found, got: AgentInfo.: 1 time, servers with issues: null; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Table 'ApplicationIndex' was not found, got: AgentInfo.: 1 time, servers with issues: null
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:760) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:298) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseApplicationIndexDao.insert(HbaseApplicationIndexDao.java:72) ~[classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseApplicationIndexDao$$FastClassBySpringCGLIB$$9475ae3b.invoke(<generated>) ~[classes!/:2.4.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseApplicationIndexDao$$EnhancerBySpringCGLIB$$6e4b1f05.insert(<generated>) ~[classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.service.AgentInfoService.insert(AgentInfoService.java:45) ~[classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.handler.grpc.GrpcAgentInfoHandler.handleAgentInfo(GrpcAgentInfoHandler.java:88) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.handler.grpc.GrpcAgentInfoHandler.handleRequest(GrpcAgentInfoHandler.java:71) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.AgentDispatchHandler.dispatchRequestMessage(AgentDispatchHandler.java:88) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchRequestMessage(DelegateDispatchHandler.java:70) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.grpc.service.SimpleRequestHandlerAdaptor.request(SimpleRequestHandlerAdaptor.java:54) [classes!/:2.4.0]
        at com.navercorp.pinpoint.collector.receiver.grpc.service.AgentService$1.run(AgentService.java:78) [classes!/:2.4.0]
        at io.grpc.Context$1.run(Context.java:566) [grpc-context-1.43.2.jar!/:1.43.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Table 'ApplicationIndex' was not found, got: AgentInfo.: 1 time, servers with issues: null
        at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.makeException(AsyncProcess.java:295) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.access$2300(AsyncProcess.java:271) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.AsyncProcess.waitForAllPreviousOpsAndReset(AsyncProcess.java:1924) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:303) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:266) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1477) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1024) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$7.doInTable(HbaseTemplate2.java:301) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:751) ~[pinpoint-commons-hbase-2.4.0.jar!/:2.4.0]
        ... 23 more

```

**Comment by julie0005** [comment]
Do you know the reason of this? Is it problem?
