### ISSUE TITLE
Error creating bean with name 'com.navercorp.pinpoint.common.hbase.HbaseVersionCheckBean#0' defined in class path resource [applicationContext-web-hbase.xml]

### ISSUE THREAD

**Issue by rahul70422** [pinpoint-apm/pinpoint#9399]
#### What version of pinpoint are you using?
2.4.2

#### Describe your problem**
not able to create the webhook

#### Logs
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
11-08 11:40:13.013 [           main] ERROR o.s.b.SpringApplication                  -- Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.navercorp.pinpoint.common.hbase.HbaseVersionCheckBean#0' defined in class path resource [applicationContext-web-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: callTimeout=10000, callDuration=18887: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)
 ; nested exception is java.net.SocketTimeoutException: callTimeout=10000, callDuration=18887: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)
 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.5.12.jar!/:2.5.12]
	at com.navercorp.pinpoint.common.server.starter.BasicStarter.start(BasicStarter.java:53) [pinpoint-commons-server-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.batch.BatchApp.main(BatchApp.java:46) [classes!/:2.4.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [pinpoint-batch.jar:2.4.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [pinpoint-batch.jar:2.4.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [pinpoint-batch.jar:2.4.2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [pinpoint-batch.jar:2.4.2]
Caused by: com.navercorp.pinpoint.common.hbase.HbaseSystemException: callTimeout=10000, callDuration=18887: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)
 ; nested exception is java.net.SocketTimeoutException: callTimeout=10000, callDuration=18887: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)
 
	at com.navercorp.pinpoint.common.hbase.HBaseAdminTemplate.execute(HBaseAdminTemplate.java:200) ~[pinpoint-commons-hbase-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.common.hbase.HbaseVersionCheckBean.afterPropertiesSet(HbaseVersionCheckBean.java:45) ~[pinpoint-commons-hbase-2.4.2.jar!/:2.4.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.20.jar!/:5.3.20]
	... 23 more
<img width="1777" alt="Screenshot 2022-11-08 at 6 11 39 PM" src="https://user-images.githubusercontent.com/36034133/200566409-cfd7cbb2-633c-40e2-9c7f-30add7ed2c4e.png">

**Comment by ga-ram** [comment]
The error logs say pinpoint web could not start because hbase is not ready.
How did you get to the webhook page when the web server is not running?

**Comment by rahul70422** [comment]
@ga-ram Web server is running. Even i am able to setup the agent and data is also coming. And i can see all the docker component is also running. Check the attached screenshot.
<img width="1792" alt="Screenshot 2022-11-09 at 8 22 17 AM" src="https://user-images.githubusercontent.com/36034133/200725989-2d1d0ab5-aeb9-463b-be37-90fa5b852d74.png">

**Comment by ga-ram** [comment]
@rahul70422 Then you need to show me another part of your logs which is related to webhook.pinpoint. Above logs are totally unrelated. Usually webhook 500 error is related to mysql but nothing is certain without logs.

**Comment by rahul70422** [comment]
@ga-ram Can you let me know for which docker container you need the logs?

**Comment by rahul70422** [comment]
@ga-ram Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
11-15 08:02:24.024 [           main] ERROR o.s.b.SpringApplication                  -- Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.navercorp.pinpoint.common.hbase.HbaseVersionCheckBean#0' defined in class path resource [applicationContext-web-hbase.xml]: Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: callTimeout=10000, callDuration=19052: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)
 ; nested exception is java.net.SocketTimeoutException: callTimeout=10000, callDuration=19052: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)
 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) [spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.5.12.jar!/:2.5.12]
	at com.navercorp.pinpoint.common.server.starter.BasicStarter.start(BasicStarter.java:53) [pinpoint-commons-server-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.web.WebApp.main(WebApp.java:40) [classes!/:2.4.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [pinpoint-web-boot.jar:2.4.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [pinpoint-web-boot.jar:2.4.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [pinpoint-web-boot.jar:2.4.2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [pinpoint-web-boot.jar:2.4.2]
Caused by: com.navercorp.pinpoint.common.hbase.HbaseSystemException: callTimeout=10000, callDuration=19052: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2379)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getClusterStatus(MasterRpcServices.java:777)
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55652)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
	at java.lang.Thread.run(Thread.java:750)


But after that webapp started.

**Comment by ga-ram** [comment]
@rahul70422 i guess web restarted and then that error didn't occur because hbase is now initialized. Please share the logs after that when you clicked. I just found that webhook.enable option is false by default and webook functions won't work. It is weird that webhook menu is visible in sidebar menu.
To use webhook, please add highlighted line to your .env file.
![Screen Shot 2022-11-16 at 10 42 53 AM](https://user-images.githubusercontent.com/3798235/202062691-2fc14889-27a8-4d3f-8edb-fa9ed23a0b01.png)

**Comment by rahul70422** [comment]
Thanks Its working now.
