### ISSUE TITLE
AFTER error. Caused:org.redisson.connection.NodeSource.getRedisClient()Lorg/redisson/client/RedisClient; java.lang.NoSuchMethodErro

### ISSUE THREAD

**Issue by HiroC222** [pinpoint-apm/pinpoint#9417]
I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

What version of pinpoint are you using?
server : 2.2.2
agent : 2.4.2

Describe the bug

```
2022-11-15 10:15:18,336 [DubboServerHandler-10.233.72.112:20981-thread-30] INFO  c.s.h.s.impl.BestGoodsServiceImpl - rlists:[] 
11-15 10:15:18.018 [20981-thread-30] WARN  r.i.CommandAsyncServiceMethodInterceptor -- AFTER error. Caused:org.redisson.connection.NodeSource.getRedisClient()Lorg/redisson/client/RedisClient;
java.lang.NoSuchMethodError: org.redisson.connection.NodeSource.getRedisClient()Lorg/redisson/client/RedisClient;
	at com.navercorp.pinpoint.plugin.redis.redisson.interceptor.CommandAsyncServiceMethodInterceptor.toEndPoint(CommandAsyncServiceMethodInterceptor.java:143) ~[pinpoint-redis-redisson-plugin-2.4.2.jar:2.4.2]
	at com.navercorp.pinpoint.plugin.redis.redisson.interceptor.CommandAsyncServiceMethodInterceptor.doInAfterTrace(CommandAsyncServiceMethodInterceptor.java:88) ~[pinpoint-redis-redisson-plugin-2.4.2.jar:2.4.2]
	at com.navercorp.pinpoint.bootstrap.interceptor.SpanEventSimpleAroundInterceptorForPlugin.after(SpanEventSimpleAroundInterceptorForPlugin.java:91) [?:2.4.2]
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:44) [?:2.4.2]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:612) [redisson-3.5.0.jar!/:?]
```

**Comment by emeroad** [comment]
Please tell us which version of redis client you are using.

**Comment by HiroC222** [comment]
redis:3.2.8 
sentinel mode

**Comment by jaehong-kim** [comment]
@HiroC222 
Currently, only 2.x versions are supported.
I will try to support the 3.x version.

**Comment by jaehong-kim** [comment]
@HiroC222 
Use version 3.10.4 or higher instead of redisson-3.5.0.jar.
