### ISSUE TITLE
Span handle error. Caused:calleeApplicationName must not be null

### ISSUE THREAD

**Issue by ighack** [pinpoint-apm/pinpoint#9537]
`2022-12-24 15:46:24 [WARN ](c.n.p.c.h.SpanHandler              ) Span handle error. Caused:calleeApplicationName must not be null. Span:TSpan(agentId:flowcompute-cloud, applicationName:flowcompute-cloud, agentStartTime:1608596849666, transactionId:00 01 82 88 E0 BE E8 2E E3 E2 F3 E8 0A, spanId:-2565579869400611063, startTime:1671867984089, elapsed:5, rpc:/runFlow, serviceType:1010, endPoint:192.168.0.235:8789, remoteAddr:192.168.0.6, annotations:[TAnnotation(key:46, value:<TAnnotationValue intValue:200>)], flag:0, err:0, spanEventList:[TSpanEvent(sequence:3, startElapsed:1, serviceType:8200, endPoint:192.168.0.245:7004, annotations:[TAnnotation(key:310, value:<TAnnotationValue intBooleanIntBooleanValue:TIntBooleanIntBooleanValue(intValue1:0, boolValue1:false, intValue2:0, boolValue2:false)>)], depth:4, destinationId:REDIS, apiId:-190), TSpanEvent(sequence:4, startElapsed:1, serviceType:7998, annotations:[TAnnotation(key:-1, value:<TAnnotationValue stringValue:http://master-data/inf-mdb/DsfGoodsSave->4b7db996-60c9-4cfa-b14e-98ad85250fb6-三方商品资料下传云仓（Java）-分库-保存正式表>), TAnnotation(key:998, value:<TAnnotationValue stringValue:http://master-data/inf-mdb/DsfGoodsSave->4b7db996-60c9-4cfa-b14e-98ad85250fb6-三方商品资料下传云仓（Java）-分库-保存正式表>)], apiId:-314), TSpanEvent(sequence:5, startElapsed:1, endElapsed:2, serviceType:9055, annotations:[TAnnotation(key:40, value:<TAnnotationValue stringValue:http://192.168.0.24:6721/inf-mdb/DsfGoodsSave>)], nextSpanId:-7370658184384928456, destinationId:192.168.0.24:6721, apiId:-8), TSpanEvent(sequence:2, startElapsed:1, endElapsed:4, serviceType:5071, depth:3, apiId:291), TSpanEvent(sequence:1, startElapsed:0, endElapsed:5, serviceType:5051, depth:2, apiId:-10), TSpanEvent(sequence:0, startElapsed:0, endElapsed:5, serviceType:1011, depth:1, apiId:294)], apiId:-295, applicationServiceType:1210, loggingTransactionInfo:0)
java.lang.NullPointerException: calleeApplicationName must not be null
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapStatisticsCallerDao.update(HbaseMapStatisticsCallerDao.java:91)
	at com.navercorp.pinpoint.collector.handler.StatisticsHandler.updateCaller(StatisticsHandler.java:59)
	at com.navercorp.pinpoint.collector.handler.SpanHandler.insertSpanEventStat(SpanHandler.java:193)
	at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:100)
	at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:72)
	at com.navercorp.pinpoint.collector.receiver.SpanDispatchHandler.dispatchSendMessage(SpanDispatchHandler.java:64)
	at com.navercorp.pinpoint.collector.receiver.DelegateDispatchHandler.dispatchSendMessage(DelegateDispatchHandler.java:56)
	at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:97)
	at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:72)
	at com.navercorp.pinpoint.collector.receiver.udp.Task.run(Task.java:44)
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
^C
pinpoint@yces42:/pinpoint/app/pinpoint/apache-tomcat-8.5.11/lo`

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/issues/4949
It seems to be an old version bug. Version upgrade is recommended.
