### ISSUE TITLE
ApplicationMapStatisticsSelf_Ver2 increment error Caused:Failed to get user region lock in10000 ms.

### ISSUE THREAD

**Issue by elther** [pinpoint-apm/pinpoint#9545]
12-28 03:39:07.007 [oFlusher-LINK-3] WARN  c.n.p.c.h.HbaseTemplate2                 : ApplicationMapStatisticsSelf_Ver2 increment error Caused:Failed to get user region lock in10000 ms.  for accessing meta region server.
org.apache.hadoop.hbase.exceptions.LockTimeoutException: Failed to get user region lock in10000 ms.  for accessing meta region server.
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.takeUserRegionLock(ConnectionManager.java:1428) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1315) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1219) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1203) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1160) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getRegionLocation(ConnectionManager.java:992) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.HRegionLocator.getRegionLocation(HRegionLocator.java:69) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:87) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:141) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at org.apache.hadoop.hbase.client.HTable.increment(HTable.java:1152) ~[hbase-shaded-client-1.7.1.jar!/:1.7.1]
	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$16.doInTable(HbaseTemplate2.java:707) [pinpoint-commons-hbase-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$16.doInTable(HbaseTemplate2.java:699) [pinpoint-commons-hbase-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:751) [pinpoint-commons-hbase-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.increment(HbaseTemplate2.java:699) [pinpoint-commons-hbase-2.4.2.jar!/:2.4.2]
	at com.navercorp.pinpoint.collector.dao.hbase.statistics.DefaultBulkWriter.flushLink(DefaultBulkWriter.java:80) [classes!/:2.4.2]
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapResponseTimeDao.flushLink(HbaseMapResponseTimeDao.java:119) [classes!/:2.4.2]
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapResponseTimeDao$$FastClassBySpringCGLIB$$b02c6c3d.invoke(<generated>) [classes!/:2.4.2]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) [spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) [spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) [spring-tx-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) [spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) [spring-aop-5.3.20.jar!/:5.3.20]
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapResponseTimeDao$$EnhancerBySpringCGLIB$$69e22132.flushLink(<generated>) [classes!/:2.4.2]
	at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.20.jar!/:5.3.20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

pinpoint 2.4.2 docker install 참고해서 설치했습니다. 
서비스 올려놓고 조금 기다리면 region lock 걸리면서 장애가 발생하는데
hbase 세팅에 문제가 있는걸까요?

**Comment by ga-ram** [comment]
It would be great if you can also describe your situation in english for the community.
Mentioned hbase error usually occurs when hbase is unstable.
Please try restarting pinpoint-hbase and check collector logs again after commands updating hbase table are finished (current docker compose script always updates all tables when starting pinpoint-hbase).
If this error still occurs after hbase restart, try removing all related volumes (with `docker volume ls` and `docker volume rm`) and then restart with docker compose. (**this erases all hbase data**)
It also may happen when your local resources are not sufficient. In this case consider allocating more resources for docker.
Since it may be too much for one machine to handle all pinpoint components, it is recommended to set up your own hbase cluster for heavy uses.

**Comment by elther** [comment]
thank you for advice. i'll do describe in english next time
