### ISSUE TITLE
Change the length of agentId from 24 to 72

### ISSUE THREAD

**Issue by DeveloperLiMingHui** [pinpoint-apm/pinpoint#9813]
Change the length of agentId from 24 to 72:
`
// change the code
// commons/src/main/java/com/navercorp/pinpoint/common/PinpointConstants.java
public final class PinpointConstants {
    //public static final int APPLICATION_NAME_MAX_LEN = 24;
    public static final int APPLICATION_NAME_MAX_LEN = 72;
    //public static final int AGENT_ID_MAX_LEN = 24;
    public static final int AGENT_ID_MAX_LEN = 72;
    public static final int AGENT_NAME_MAX_LEN = 255;
}
// errors
`
`03-31 17:46:17.017 [-Executor(12-0)] WARN  c.n.p.p.r.g.GrpcCommandService           -- Failed to command stream, cause=INVALID_ARGUMENT: INVALID_ARGUMENT: invalid agentid
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: INVALID_ARGUMENT: invalid agentid
        at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.36.2.jar:1.36.2]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.36.2.jar:1.36.2]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.36.2.jar:2.3.4-SNAPSHOT]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.36.2.jar:2.3.4-SNAPSHOT]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.36.2.jar:2.3.4-SNAPSHOT]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.36.2.jar:2.3.4-SNAPSHOT]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.36.2.jar:2.3.4-SNAPSHOT]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.36.2.jar:2.3.4-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

what should I do?

**Comment by emeroad** [comment]
We recommend using agentName instead of agentId.
If you do not set agentId, the pinpoint agent automatically assigns a UUID.
`-Dpinpoint.agentName=test-agent`
