### ISSUE TITLE
Zookeeper issue while triggering Pinpoint collector

### ISSUE THREAD

**Issue by avanishec** [pinpoint-apm/pinpoint#9956]
Hi Team,
Need your help to resolve the below issue .

I am having the following error while running Pinpoint Collector:

 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.14.jar!/:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
05-18 15:44:10.010 [localhost:2181)] WARN  o.a.z.ClientCnxn                         : Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address localhost/<unresolved>:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar!/:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[zookeeper-3.4.14.jar!/:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]

I am using the follwoing software version in our machine:

hbase- 1.2.12
zookeeper - zookeeper-3.4.14
pinpoint -  2.5.1

please suggest me what went wrong in my environment.

**Comment by jiayuju** [comment]
localhost replace 127.0.0.1   ,try

**Comment by emeroad** [comment]
https://pinpoint-apm.gitbook.io/pinpoint/getting-started/installation#routing-web-requests-to-agents
It looks like the error log of the realtime feature.
Would you like to see the link above?
